//! The bash pack, which also takes POSIX sh: tree-sitter-bash parses both without ERROR.
//!
//! - It has no doc syntax, so position decides. A run directly above a function documents it, and
//!   otherwise the first prose run of a file documents the file when no code precedes it — the two
//!   headers the Google Shell Style Guide asks for.
//! - Any sentence is a valid command with arguments, so a clean parse says nothing about whether a
//!   comment is code. [`is_code`] asks for shell syntax instead.

use crate::common::{Container, Excluded, alone_on_its_line, count_members, declarations};
use laconic_engine::domain::{CommentKind, DeclaredSymbol, Visibility};
use laconic_engine::exclude::is_licence_text;
use laconic_engine::is_shebang;
use laconic_engine::pack::{BlankLinePolicy, DocComment, Pack, split_identifier};
use laconic_grammars::Grammar;
use tree_sitter::Node;

const EXTENSIONS: &[(&str, Grammar)] = &[("sh", Grammar::Bash), ("bash", Grammar::Bash)];
const INTERPRETERS: &[(&str, Grammar)] = &[("bash", Grammar::Bash), ("sh", Grammar::Bash)];
pub(crate) const COMMENT_KINDS: &[&str] = &["comment"];

/// Concern 3, matched against the body after `#`. The shebang is the engine's, by position.
const MACHINE_DIRECTIVES: &[&str] = &["shellcheck "];

/// With the comment leader, because the markers are matched on raw text and a generator script
/// writes the bare ones into the file it generates.
const GENERATED_MARKERS: &[&str] = &["# @generated", "# Code generated by ", "# DO NOT EDIT"];

const STATEMENTS: Excluded = Excluded {
    reason: "a statement: code that runs and names nothing",
    kinds: &[
        "c_style_for_statement",
        "case_statement",
        "command",
        "compound_statement",
        "declaration_command",
        "for_statement",
        "if_statement",
        "list",
        "negated_command",
        "pipeline",
        "redirected_statement",
        "subshell",
        "test_command",
        "unset_command",
        "variable_assignment",
        "variable_assignments",
        "while_statement",
    ],
};

/// A function defined under a conditional or a loop is not a subject. `if ! command -v x; then
/// x() {…}; fi` is a real idiom, but whether it is defined depends on a run, not on the file.
pub(crate) const CONTAINERS: &[Container] = &[
    Container {
        kind: "program",
        within: &[],
        declarations: &["function_definition"],
        wrappers: &[],
        excluded: &[STATEMENTS],
    },
    Container {
        kind: "compound_statement",
        within: &[],
        declarations: &["function_definition"],
        wrappers: &[],
        excluded: &[
            STATEMENTS,
            Excluded {
                reason: "the arithmetic inside `(( … ))`, which is an expression",
                kinds: &[
                    "binary_expression",
                    "command_substitution",
                    "expansion",
                    "number",
                    "parenthesized_expression",
                    "postfix_expression",
                    "raw_string",
                    "simple_expansion",
                    "string",
                    "subscript",
                    "ternary_expression",
                    "unary_expression",
                    "variable_name",
                ],
            },
        ],
    },
];

/// Node kinds that only shell code produces. A sentence parses to a `command` of plain words.
const SHELL_SYNTAX: &[&str] = &[
    "arithmetic_expansion",
    "c_style_for_statement",
    "case_statement",
    "command_substitution",
    "compound_statement",
    "declaration_command",
    "expansion",
    "file_redirect",
    "for_statement",
    "function_definition",
    "heredoc_redirect",
    "herestring_redirect",
    "if_statement",
    "list",
    "negated_command",
    "pipeline",
    "process_substitution",
    "simple_expansion",
    "subshell",
    "test_command",
    "unset_command",
    "variable_assignment",
    "while_statement",
];

pub struct BashPack;

impl Pack for BashPack {
    fn name(&self) -> &'static str {
        "bash"
    }

    fn extensions(&self) -> &[(&'static str, Grammar)] {
        EXTENSIONS
    }

    fn interpreters(&self) -> &[(&'static str, Grammar)] {
        INTERPRETERS
    }

    fn comment_node_kinds(&self, _grammar: Grammar) -> &[&'static str] {
        COMMENT_KINDS
    }

    fn machine_directive_prefixes(&self) -> &[&'static str] {
        MACHINE_DIRECTIVES
    }

    fn generated_file_markers(&self) -> &[&'static str] {
        GENERATED_MARKERS
    }

    fn comment_kind(&self, _node: Node, _src: &str) -> CommentKind {
        CommentKind::Line
    }

    fn doc_comments<'t>(&self, root: Node<'t>, src: &str) -> Vec<DocComment<'t>> {
        let functions = declarations(CONTAINERS, root);
        let mut out: Vec<DocComment<'t>> = functions
            .iter()
            .filter_map(|f| header_above(*f, src).map(|node| DocComment { node, subject: *f }))
            .collect();
        if let Some(node) = file_header(root, src)
            && !out.iter().any(|d| d.node.id() == node.id())
        {
            out.push(DocComment {
                node,
                subject: root,
            });
        }
        out.sort_by_key(|d| d.node.start_byte());
        out
    }

    fn subject_nodes<'t>(&self, root: Node<'t>) -> Vec<Node<'t>> {
        let mut out = vec![root];
        out.extend(declarations(CONTAINERS, root));
        out
    }

    fn comment_body(&self, node: Node, src: &str) -> String {
        body(node, src).to_string()
    }

    /// Sourcing makes every function reachable, so the leading underscore is the only signal there
    /// is.
    fn visibility(&self, subject: Node, src: &str) -> Visibility {
        match subject.child_by_field_name("name") {
            Some(name) if src[name.byte_range()].starts_with('_') => Visibility::Private,
            _ => Visibility::Exported,
        }
    }

    fn member_count(&self, subject: Node, _src: &str) -> usize {
        let body = subject.child_by_field_name("body").unwrap_or(subject);
        count_members(body, &[])
    }

    fn blank_line_policy(&self) -> BlankLinePolicy {
        BlankLinePolicy::CollapseRun
    }

    fn is_code(&self) -> fn(Node, &str) -> bool {
        is_code
    }

    fn path_reference_extensions(&self) -> Vec<&'static str> {
        Vec::new()
    }

    fn declared_symbols(&self, root: Node, src: &str) -> Vec<DeclaredSymbol> {
        let mut out = Vec::new();
        for f in declarations(CONTAINERS, root) {
            if let Some(name) = f.child_by_field_name("name") {
                push_symbol(&mut out, &src[name.byte_range()], "function");
            }
        }
        let mut cursor = root.walk();
        for statement in root.named_children(&mut cursor) {
            for assignment in assignments(statement) {
                if let Some(name) = assignment.child_by_field_name("name") {
                    push_symbol(&mut out, &src[name.byte_range()], "variable");
                }
            }
        }
        out
    }

    /// A function's name, an assignment's variable, a command's name — never its arguments, which
    /// are data, and never a function's body.
    fn bound_identifiers(&self, subject: Node, src: &str) -> Vec<String> {
        let body = subject.child_by_field_name("body").map(|b| b.id());
        let mut cursor = subject.walk();
        let mut stack = vec![subject];
        let mut out = Vec::new();
        while let Some(n) = stack.pop() {
            let bound = match n.kind() {
                "command_name" => true,
                "variable_name" => n.parent().is_some_and(|p| {
                    p.kind() == "variable_assignment"
                        && p.child_by_field_name("name").map(|v| v.id()) == Some(n.id())
                }),
                "word" => n.parent().is_some_and(|p| {
                    p.kind() == "function_definition"
                        && p.child_by_field_name("name").map(|w| w.id()) == Some(n.id())
                }),
                _ => false,
            };
            if bound {
                out.extend(split_identifier(&src[n.byte_range()]));
            }
            for c in n.named_children(&mut cursor) {
                if Some(c.id()) != body {
                    stack.push(c);
                }
            }
        }
        out.sort();
        out.dedup();
        out
    }
}

fn body<'s>(node: Node, src: &'s str) -> &'s str {
    let raw = &src[node.byte_range()];
    raw.strip_prefix('#').unwrap_or(raw).trim_end()
}

fn is_directive(node: Node, src: &str) -> bool {
    let trimmed = body(node, src).trim_start();
    is_shebang(node.start_byte(), src) || MACHINE_DIRECTIVES.iter().any(|p| trimmed.starts_with(p))
}

/// The nearest prose comment in the run directly above `function`, walking over directives.
fn header_above<'t>(function: Node<'t>, src: &str) -> Option<Node<'t>> {
    let mut below_row = function.start_position().row;
    let mut candidate = function.prev_sibling();
    while let Some(prev) = candidate {
        let adjacent = prev.end_position().row + 1 == below_row;
        if prev.kind() != "comment" || !adjacent || !alone_on_its_line(prev, src) {
            return None;
        }
        if !is_directive(prev, src) {
            return Some(prev);
        }
        below_row = prev.start_position().row;
        candidate = prev.prev_sibling();
    }
    None
}

/// A prose comment from the file's first run that is not only directives, when no code precedes
/// it and it does not sit directly above a function — that one is the function's header.
fn file_header<'t>(root: Node<'t>, src: &str) -> Option<Node<'t>> {
    let mut cursor = root.walk();
    let children: Vec<Node<'t>> = root.children(&mut cursor).collect();
    let mut i = 0;
    while i < children.len() && children[i].kind() == "comment" {
        let start = i;
        while i + 1 < children.len()
            && children[i + 1].kind() == "comment"
            && children[i + 1].start_position().row == children[i].end_position().row + 1
        {
            i += 1;
        }
        let run = &children[start..=i];
        i += 1;
        let Some(prose) = run.iter().find(|c| !is_directive(**c, src)) else {
            continue;
        };
        let text: Vec<&str> = run.iter().map(|c| body(*c, src)).collect();
        if is_licence_text(&text.join("\n")) {
            continue;
        }
        let below = children.get(i);
        let above_a_function = below.is_some_and(|n| {
            n.kind() == "function_definition"
                && n.start_position().row == run[run.len() - 1].end_position().row + 1
        });
        return (!above_a_function).then_some(*prose);
    }
    None
}

/// Whether a comment body is a command: it carries shell syntax — an expansion, a pipe, a redirect,
/// an assignment, a compound command or a `-flag` — and does not read as a sentence.
pub(crate) fn is_code(root: Node, src: &str) -> bool {
    if reads_as_prose(root, src) {
        return false;
    }
    let mut cursor = root.walk();
    let mut stack = vec![root];
    while let Some(n) = stack.pop() {
        // A backtick pair in prose is a Markdown code span, and the grammar reads it as a command
        // substitution. Real code reaches for `$(…)`, so nothing inside backticks is evidence.
        if is_backtick_substitution(n, src) {
            continue;
        }
        if SHELL_SYNTAX.contains(&n.kind()) {
            return true;
        }
        if n.kind() == "word"
            && n.parent().is_some_and(|p| p.kind() == "command")
            && is_flag(&src[n.byte_range()])
        {
            return true;
        }
        stack.extend(n.named_children(&mut cursor));
    }
    false
}

/// Words a sentence cannot do without and a command line almost never passes as an argument.
const FUNCTION_WORDS: &[&str] = &[
    "a", "after", "an", "and", "are", "as", "at", "be", "before", "by", "for", "from", "in",
    "into", "is", "no", "not", "of", "on", "or", "over", "so", "than", "the", "to", "was", "when",
    "with",
];

/// Whether the body is a sentence that mentions shell rather than a command: a bare word is an
/// English function word, or ends a clause (`here.`, `name,`), or the text draws an arrow. A
/// `-flag` is never prose, so `cut -d:` stays code.
fn reads_as_prose(root: Node, src: &str) -> bool {
    let text = &src[root.byte_range()];
    if ["->", "=>", "<-"].iter().any(|arrow| text.contains(arrow)) {
        return true;
    }
    let mut cursor = root.walk();
    let mut stack = vec![root];
    while let Some(n) = stack.pop() {
        if matches!(n.kind(), "word" | "concatenation" | "variable_name") {
            let word = &src[n.byte_range()];
            if !word.starts_with('-')
                && (FUNCTION_WORDS.contains(&word.to_lowercase().as_str()) || ends_a_clause(word))
            {
                return true;
            }
        }
        stack.extend(n.named_children(&mut cursor));
    }
    false
}

/// `here.` or `name,` — a clause mark after a word. `;` alone is an operator, and `cd ..` ends in no
/// letter.
fn ends_a_clause(word: &str) -> bool {
    let mut tail = word.chars().rev();
    tail.next().is_some_and(|c| ".,:;!?".contains(c))
        && tail
            .next()
            .is_some_and(|c| c.is_alphanumeric() || "\"'`)".contains(c))
}

fn is_backtick_substitution(node: Node, src: &str) -> bool {
    node.kind() == "command_substitution" && src[node.byte_range()].starts_with('`')
}

fn is_flag(word: &str) -> bool {
    let name = word.trim_start_matches('-');
    word.len() - name.len() <= 2 && word.starts_with('-') && name.starts_with(char::is_alphanumeric)
}

/// The assignments a top-level statement makes: `X=1`, `readonly X=1`, `export X=1`.
fn assignments(statement: Node<'_>) -> Vec<Node<'_>> {
    match statement.kind() {
        "variable_assignment" => vec![statement],
        "variable_assignments" | "declaration_command" => {
            let mut cursor = statement.walk();
            statement
                .named_children(&mut cursor)
                .filter(|n| n.kind() == "variable_assignment")
                .collect()
        }
        _ => Vec::new(),
    }
}

fn push_symbol(out: &mut Vec<DeclaredSymbol>, name: &str, form: &'static str) {
    out.push(DeclaredSymbol {
        visibility: if name.starts_with('_') {
            Visibility::Private
        } else {
            Visibility::Exported
        },
        name: name.to_string(),
        form,
    });
}
