//! The Go pack.
//!
//! Go is the pack the engine was built against, chosen because its doc comment is positional —
//! the mechanism most likely to expose a positional assumption hiding in the engine rather than
//! in a pack.

use laconic_engine::domain::{CommentKind, DeclaredSymbol, Visibility};
use laconic_engine::pack::{BlankLinePolicy, DocComment, Pack};
use laconic_grammars::Grammar;
use tree_sitter::Node;

const EXTENSIONS: &[(&str, Grammar)] = &[("go", Grammar::Go)];
const COMMENT_KINDS: &[&str] = &["comment"];

/// Concern 3. Bodies arrive with `//` already stripped, so these match the text that follows it.
///
/// `//go:build` is here rather than being special-cased by `detached`: stripping it as a directive
/// means no rule ever reaches it, so no rule needs to know what a build constraint is.
const MACHINE_DIRECTIVES: &[&str] = &["go:", "nolint:", "lint:ignore", "+build", "export ", "cgo "];

const GENERATED_MARKERS: &[&str] = &["Code generated by "];

/// Declarations that can carry a godoc comment, in the grammar's vocabulary.
const DOCUMENTABLE: &[&str] = &[
    "function_declaration",
    "method_declaration",
    "type_declaration",
    "const_declaration",
    "var_declaration",
];

pub struct GoPack;

impl Pack for GoPack {
    fn name(&self) -> &'static str {
        "go"
    }

    fn extensions(&self) -> &[(&'static str, Grammar)] {
        EXTENSIONS
    }

    fn comment_node_kinds(&self, _grammar: Grammar) -> &[&'static str] {
        COMMENT_KINDS
    }

    fn machine_directive_prefixes(&self) -> &[&'static str] {
        MACHINE_DIRECTIVES
    }

    fn generated_file_markers(&self) -> &[&'static str] {
        GENERATED_MARKERS
    }

    fn comment_kind(&self, node: Node, src: &str) -> CommentKind {
        if src[node.byte_range()].starts_with("/*") {
            CommentKind::Block
        } else {
            CommentKind::Line
        }
    }

    /// Concern 6 — position, with no lexical signal at all. The doc comment is the comment ending
    /// on the line directly above a declaration; the same node kind two lines up is not one.
    fn doc_comments<'t>(&self, root: Node<'t>, _src: &str) -> Vec<DocComment<'t>> {
        let mut cursor = root.walk();
        let mut stack = vec![root];
        let mut out = Vec::new();
        while let Some(n) = stack.pop() {
            for child in n.named_children(&mut cursor) {
                if DOCUMENTABLE.contains(&child.kind())
                    && let Some(prev) = child.prev_sibling()
                    && prev.kind() == "comment"
                    && prev.end_position().row + 1 == child.start_position().row
                {
                    out.push(DocComment {
                        node: prev,
                        subject: child,
                    });
                }
                stack.push(child);
            }
        }
        out
    }

    fn comment_body(&self, node: Node, src: &str) -> String {
        strip_markers(&src[node.byte_range()])
    }

    fn visibility(&self, subject: Node, src: &str) -> Visibility {
        match declared_name(subject, src) {
            Some(name) if name.starts_with(char::is_uppercase) => Visibility::Exported,
            _ => Visibility::Private,
        }
    }

    /// Concern 9. Go interposes a `statement_list` between `block` and its statements: counting
    /// `block`'s named children directly gives every function a statement count of one and makes
    /// `density`'s ratio meaningless.
    fn statement_count(&self, subject: Node, _src: &str) -> usize {
        let Some(body) = subject.child_by_field_name("body") else {
            return 0;
        };
        let mut cursor = body.walk();
        let Some(list) = body
            .named_children(&mut cursor)
            .find(|n| n.kind() == "statement_list")
        else {
            return 0;
        };
        let mut cursor = list.walk();
        list.named_children(&mut cursor)
            .filter(|n| !n.is_extra())
            .count()
    }

    fn blank_line_policy(&self) -> BlankLinePolicy {
        BlankLinePolicy::CollapseRun
    }

    /// Concern 11. Top-level declarations are named children of the root, and every form but
    /// `func` nests its name one level down in a `_spec` node.
    fn declared_symbols(&self, root: Node, src: &str) -> Vec<DeclaredSymbol> {
        let mut cursor = root.walk();
        let mut out = Vec::new();
        for decl in root.named_children(&mut cursor) {
            let (spec_kind, form) = match decl.kind() {
                "function_declaration" | "method_declaration" => {
                    if let Some(name) = declared_name(decl, src) {
                        out.push(symbol(name, "func"));
                    }
                    continue;
                }
                "type_declaration" => ("type_spec", "type"),
                "const_declaration" => ("const_spec", "const"),
                "var_declaration" => ("var_spec", "var"),
                _ => continue,
            };
            let mut inner = decl.walk();
            for spec in decl.named_children(&mut inner) {
                if spec.kind() == spec_kind
                    && let Some(name) = declared_name(spec, src)
                {
                    out.push(symbol(name, form));
                }
            }
        }
        out
    }
}

fn symbol(name: &str, form: &'static str) -> DeclaredSymbol {
    DeclaredSymbol {
        visibility: if name.starts_with(char::is_uppercase) {
            Visibility::Exported
        } else {
            Visibility::Private
        },
        name: name.to_string(),
        form,
    }
}

fn declared_name<'a>(node: Node, src: &'a str) -> Option<&'a str> {
    node.child_by_field_name("name")
        .map(|n| &src[n.byte_range()])
}

/// Concern 7. `banner` matches repeated punctuation, so leaving `//` on the body both misses
/// `// =====` and turns every comment into one that starts with punctuation.
///
/// Only the marker and the `*` continuation leader come off. **Leading whitespace after the marker
/// stays**, uniformly for both comment kinds: `commentedOutCode` parses the body in the file's own
/// language, and a pack that trimmed each line would destroy the relative indentation an
/// indentation-significant language needs to parse at all.
fn strip_markers(raw: &str) -> String {
    if let Some(rest) = raw.strip_prefix("//") {
        return rest.trim_end().to_string();
    }
    let inner = raw
        .strip_prefix("/*")
        .and_then(|r| r.strip_suffix("*/"))
        .unwrap_or(raw);
    inner
        .lines()
        .map(strip_continuation_leader)
        .collect::<Vec<_>>()
        .join("\n")
        .trim_matches('\n')
        .to_string()
}

/// `  * text` becomes ` text`; a line with no leader is returned as it stands.
fn strip_continuation_leader(line: &str) -> &str {
    let trimmed = line.trim_end();
    let indent = trimmed.len() - trimmed.trim_start().len();
    match trimmed[indent..].strip_prefix('*') {
        Some(rest) => rest,
        None => trimmed,
    }
}
