//! The Go pack.
//!
//! Go is the pack the engine was built against, chosen because its doc comment is positional —
//! the mechanism most likely to expose a positional assumption hiding in the engine rather than
//! in a pack.

use laconic_engine::domain::{CommentKind, DeclaredSymbol, Visibility};
use laconic_engine::pack::{BlankLinePolicy, DocComment, Pack};
use laconic_grammars::Grammar;
use tree_sitter::Node;

const EXTENSIONS: &[(&str, Grammar)] = &[("go", Grammar::Go)];
const COMMENT_KINDS: &[&str] = &["comment"];

/// Concern 3. Bodies arrive with `//` already stripped, so these match the text that follows it.
///
/// `//go:build` is here rather than being special-cased by `detached`: stripping it as a directive
/// means no rule ever reaches it, so no rule needs to know what a build constraint is.
///
/// `//export Name` is cgo's export directive; the preamble form is `// #cgo CFLAGS: …`, whose
/// stripped body opens with `#cgo`. A `"cgo "` prefix would miss the real directive and swallow
/// ordinary prose like "cgo requires this above the import" instead.
const MACHINE_DIRECTIVES: &[&str] = &["go:", "nolint:", "lint:ignore", "+build", "export ", "#cgo"];

const GENERATED_MARKERS: &[&str] = &["Code generated by "];

/// Declarations that can carry a godoc comment, wherever they appear.
const DOCUMENTABLE_ANYWHERE: &[&str] = &[
    "function_declaration",
    "method_declaration",
    // A struct field is a godoc surface. An interface method is a `method_elem`, not a
    // `field_declaration` — `field_declaration` occurs only under `field_declaration_list` in a
    // struct — and without it the comment above an exported interface method is Line kind, which
    // carries a Delete fix at gate tier with autofix on.
    "field_declaration",
    "method_elem",
    // `// Package x ...` is the package doc comment and the first thing pkg.go.dev shows. Without
    // it here the block is Line kind, which carries a Delete fix at gate tier with autofix on —
    // `laconic fix` would delete a package comment that tripped `narration` or `banner`.
    "package_clause",
];

/// Declarations that carry a godoc comment only at file scope. `var`, `const` and `type` are also
/// ordinary statements inside a function body, where a comment above one documents nothing public.
const DOCUMENTABLE_AT_FILE_SCOPE: &[&str] =
    &["type_declaration", "const_declaration", "var_declaration"];

fn is_documentable(node: Node) -> bool {
    if DOCUMENTABLE_ANYWHERE.contains(&node.kind()) {
        return true;
    }
    DOCUMENTABLE_AT_FILE_SCOPE.contains(&node.kind())
        && node.parent().is_some_and(|p| p.kind() == "source_file")
}

pub struct GoPack;

impl Pack for GoPack {
    fn name(&self) -> &'static str {
        "go"
    }

    fn extensions(&self) -> &[(&'static str, Grammar)] {
        EXTENSIONS
    }

    fn comment_node_kinds(&self, _grammar: Grammar) -> &[&'static str] {
        COMMENT_KINDS
    }

    fn machine_directive_prefixes(&self) -> &[&'static str] {
        MACHINE_DIRECTIVES
    }

    fn generated_file_markers(&self) -> &[&'static str] {
        GENERATED_MARKERS
    }

    fn comment_kind(&self, node: Node, src: &str) -> CommentKind {
        if src[node.byte_range()].starts_with("/*") {
            CommentKind::Block
        } else {
            CommentKind::Line
        }
    }

    /// Concern 6 — position, with no lexical signal at all. The doc comment is the comment ending
    /// on the line directly above a declaration; the same node kind two lines up is not one.
    fn doc_comments<'t>(&self, root: Node<'t>, src: &str) -> Vec<DocComment<'t>> {
        let mut cursor = root.walk();
        let mut stack = vec![root];
        let mut out = Vec::new();
        while let Some(n) = stack.pop() {
            for child in n.named_children(&mut cursor) {
                if is_documentable(child)
                    && let Some(prev) = child.prev_sibling()
                    && prev.kind() == "comment"
                    && prev.end_position().row + 1 == child.start_position().row
                    && alone_on_its_line(prev, src)
                {
                    out.push(DocComment {
                        node: prev,
                        subject: child,
                    });
                }
                stack.push(child);
            }
        }
        out
    }

    /// Concern 6's other half. The same set `doc_comments` scans, minus the requirement that a
    /// comment actually sits above the declaration.
    fn subject_nodes<'t>(&self, root: Node<'t>) -> Vec<Node<'t>> {
        let mut cursor = root.walk();
        let mut stack = vec![root];
        let mut out = Vec::new();
        while let Some(n) = stack.pop() {
            for child in n.named_children(&mut cursor) {
                if is_documentable(child) {
                    out.push(child);
                }
                stack.push(child);
            }
        }
        out.sort_by_key(|n| n.start_byte());
        out
    }

    fn comment_body(&self, node: Node, src: &str) -> String {
        strip_markers(&src[node.byte_range()])
    }

    /// The first rune's case. An unexported top-level identifier is **not** `Private`: it is
    /// reachable from every other file in the same package, which is what `Restricted` describes.
    /// A `package_clause` declares no `name` field, so it falls to the `None` arm — and read as
    /// package-restricted it made `implInInterface`, which opens by requiring an exported subject,
    /// permanently silent on the package doc comment. That comment is the most widely published
    /// surface Go has, and an unexported name leaked into it is what decision 23 exists to catch.
    fn visibility(&self, subject: Node, src: &str) -> Visibility {
        if subject.kind() == "package_clause" {
            return Visibility::Exported;
        }
        match declared_name(subject, src) {
            Some(name) => go_visibility(name),
            None => Visibility::Restricted(PACKAGE.to_string()),
        }
    }

    /// Concern 9. Go interposes a `statement_list` between `block` and its statements: counting
    /// `block`'s named children directly gives every function a statement count of one and makes
    /// `density`'s ratio meaningless.
    fn statement_count(&self, subject: Node, _src: &str) -> usize {
        let Some(body) = subject.child_by_field_name("body") else {
            return 0;
        };
        let mut cursor = body.walk();
        let Some(list) = body
            .named_children(&mut cursor)
            .find(|n| n.kind() == "statement_list")
        else {
            return 0;
        };
        let mut cursor = list.walk();
        list.named_children(&mut cursor)
            .filter(|n| !n.is_extra())
            .count()
    }

    fn blank_line_policy(&self) -> BlankLinePolicy {
        BlankLinePolicy::CollapseRun
    }

    /// Concern 11. Top-level declarations are named children of the root, and every form but
    /// `func` nests its name one level down in a `_spec` node.
    fn declared_symbols(&self, root: Node, src: &str) -> Vec<DeclaredSymbol> {
        let mut cursor = root.walk();
        let mut out = Vec::new();
        for decl in root.named_children(&mut cursor) {
            let (spec_kind, form) = match decl.kind() {
                "function_declaration" | "method_declaration" => {
                    if let Some(name) = declared_name(decl, src) {
                        out.push(symbol(name, "func"));
                    }
                    continue;
                }
                "type_declaration" => ("type_spec", "type"),
                "const_declaration" => ("const_spec", "const"),
                "var_declaration" => ("var_spec", "var"),
                _ => continue,
            };
            // Two shapes. `var_declaration` is `seq('var', choice(var_spec, var_spec_list))`, so the
            // grouped `var ( … )` form nests its specs one level further down. And a spec binds N
            // names — `var Foo, bar = 1, 2` — so reading the first `name` field alone drops every
            // later one, and `implInInterface` could not resolve `bar` as declared in this file.
            let mut inner = decl.walk();
            let specs: Vec<Node> = decl
                .named_children(&mut inner)
                .flat_map(|child| {
                    if child.kind() == spec_kind {
                        return vec![child];
                    }
                    let mut c = child.walk();
                    child
                        .named_children(&mut c)
                        .filter(|n| n.kind() == spec_kind)
                        .collect()
                })
                .collect();
            for spec in specs {
                let mut c = spec.walk();
                for name in spec.children_by_field_name("name", &mut c) {
                    out.push(symbol(&src[name.byte_range()], form));
                }
            }
        }
        out
    }
}

const PACKAGE: &str = "package";

fn go_visibility(name: &str) -> Visibility {
    if name.starts_with(char::is_uppercase) {
        Visibility::Exported
    } else {
        Visibility::Restricted(PACKAGE.to_string())
    }
}

fn symbol(name: &str, form: &'static str) -> DeclaredSymbol {
    DeclaredSymbol {
        visibility: go_visibility(name),
        name: name.to_string(),
        form,
    }
}

/// Whether only whitespace precedes the comment on its line. A trailing comment documents nothing:
/// without this, `x := 1 // note` becomes the doc comment of whatever declaration follows it.
fn alone_on_its_line(node: Node, src: &str) -> bool {
    let start = node.start_byte();
    let line_start = src[..start].rfind('\n').map_or(0, |i| i + 1);
    src[line_start..start].trim().is_empty()
}

fn declared_name<'a>(node: Node, src: &'a str) -> Option<&'a str> {
    node.child_by_field_name("name")
        .map(|n| &src[n.byte_range()])
}

/// Concern 7. `banner` matches repeated punctuation, so leaving `//` on the body both misses
/// `// =====` and turns every comment into one that starts with punctuation.
///
/// Only the marker and the `*` continuation leader come off. **Leading whitespace after the marker
/// stays**, uniformly for both comment kinds: `commentedOutCode` parses the body in the file's own
/// language, and a pack that trimmed each line would destroy the relative indentation an
/// indentation-significant language needs to parse at all.
fn strip_markers(raw: &str) -> String {
    if let Some(rest) = raw.strip_prefix("//") {
        return rest.trim_end().to_string();
    }
    let inner = raw
        .strip_prefix("/*")
        .and_then(|r| r.strip_suffix("*/"))
        .unwrap_or(raw);
    inner
        .lines()
        .map(strip_continuation_leader)
        .collect::<Vec<_>>()
        .join("\n")
        .trim_matches('\n')
        .to_string()
}

/// `  * text` becomes ` text`; a line with no leader is returned as it stands.
fn strip_continuation_leader(line: &str) -> &str {
    let trimmed = line.trim_end();
    let indent = trimmed.len() - trimmed.trim_start().len();
    match trimmed[indent..].strip_prefix('*') {
        Some(rest) => rest,
        None => trimmed,
    }
}
