//! The Java pack.
//!
//! Doc comments are marker text on an ordinary `block_comment`, because the grammar exposes no
//! field and no distinct type for one. `@SuppressWarnings` and friends are **annotations, not
//! comments** — they never reach a rule and need no carve-out.

use crate::common::{
    count_statements, declared_name, descendants_of_kind, is_marker_doc, preceding_comment,
    strip_c_markers,
};
use laconic_engine::domain::{CommentKind, DeclaredSymbol, Visibility};
use laconic_engine::pack::{BlankLinePolicy, DocComment, Pack};
use laconic_grammars::Grammar;
use tree_sitter::Node;

const EXTENSIONS: &[(&str, Grammar)] = &[("java", Grammar::Java)];
const COMMENT_KINDS: &[&str] = &["line_comment", "block_comment"];

/// Concern 3. Bodies arrive with the marker already stripped.
///
/// `$NON-NLS-1$` is the Eclipse externalised-string marker, which sits as a trailing comment on the
/// line it applies to and breaks that tooling if removed.
const MACHINE_DIRECTIVES: &[&str] = &[
    "CHECKSTYLE:",
    "SUPPRESS CHECKSTYLE",
    "NOPMD",
    "NOSONAR",
    "$NON-NLS-",
    "@formatter:",
    "spotless:",
];

const GENERATED_MARKERS: &[&str] = &["@generated", "Generated by ", "DO NOT EDIT"];

const DECLARATIONS: &[&str] = &[
    "class_declaration",
    "interface_declaration",
    "enum_declaration",
    "record_declaration",
    "annotation_type_declaration",
    "method_declaration",
    "constructor_declaration",
    "field_declaration",
];

pub struct JavaPack;

impl Pack for JavaPack {
    fn name(&self) -> &'static str {
        "java"
    }

    fn extensions(&self) -> &[(&'static str, Grammar)] {
        EXTENSIONS
    }

    fn comment_node_kinds(&self, _grammar: Grammar) -> &[&'static str] {
        COMMENT_KINDS
    }

    fn machine_directive_prefixes(&self) -> &[&'static str] {
        MACHINE_DIRECTIVES
    }

    fn generated_file_markers(&self) -> &[&'static str] {
        GENERATED_MARKERS
    }

    fn comment_kind(&self, node: Node, _src: &str) -> CommentKind {
        if node.kind() == "block_comment" {
            CommentKind::Block
        } else {
            CommentKind::Line
        }
    }

    /// Concern 6 — a `/**`-opened block comment directly above a declaration. The marker test is
    /// stricter than `starts_with("/**")`, so `/**/` and `/****/` stay ordinary block comments.
    fn doc_comments<'t>(&self, root: Node<'t>, src: &str) -> Vec<DocComment<'t>> {
        descendants_of_kind(root, DECLARATIONS)
            .into_iter()
            .filter_map(|decl| {
                let comment = preceding_comment(decl, src, COMMENT_KINDS)?;
                (comment.kind() == "block_comment" && is_marker_doc(&src[comment.byte_range()]))
                    .then_some(DocComment {
                        node: comment,
                        subject: decl,
                    })
            })
            .collect()
    }

    fn subject_nodes<'t>(&self, root: Node<'t>) -> Vec<Node<'t>> {
        descendants_of_kind(root, DECLARATIONS)
    }

    fn comment_body(&self, node: Node, src: &str) -> String {
        strip_c_markers(&src[node.byte_range()])
    }

    /// Concern 8 — a keyword child of `modifiers`. No modifier means package-private, which is
    /// reachable from other files in the package and so `Restricted`, not `Private`.
    fn visibility(&self, subject: Node, src: &str) -> Visibility {
        let _ = src;
        for (keyword, visibility) in [
            ("public", Visibility::Exported),
            ("private", Visibility::Private),
        ] {
            if crate::common::has_modifier_keyword(subject, keyword) {
                return visibility;
            }
        }
        if crate::common::has_modifier_keyword(subject, "protected") {
            return Visibility::Restricted("protected".to_string());
        }
        Visibility::Restricted("package".to_string())
    }

    fn statement_count(&self, subject: Node, _src: &str) -> usize {
        match subject.child_by_field_name("body") {
            Some(body) => count_statements(body, &[]),
            None => 0,
        }
    }

    fn blank_line_policy(&self) -> BlankLinePolicy {
        BlankLinePolicy::CollapseRun
    }

    fn declared_symbols(&self, root: Node, src: &str) -> Vec<DeclaredSymbol> {
        descendants_of_kind(root, DECLARATIONS)
            .into_iter()
            .filter_map(|decl| {
                // A field declaration names itself through a `variable_declarator`, not a `name`
                // field, so the ordinary path misses every field in the file.
                let name = declared_name(decl, src).or_else(|| field_name(decl, src))?;
                Some(DeclaredSymbol {
                    name: name.to_string(),
                    form: form_of(decl.kind()),
                    visibility: self.visibility(decl, src),
                })
            })
            .collect()
    }
}

fn field_name<'a>(decl: Node, src: &'a str) -> Option<&'a str> {
    if decl.kind() != "field_declaration" {
        return None;
    }
    let mut cursor = decl.walk();
    let declarator = decl
        .named_children(&mut cursor)
        .find(|n| n.kind() == "variable_declarator")?;
    declared_name(declarator, src)
}

fn form_of(kind: &str) -> &'static str {
    match kind {
        "class_declaration" => "class",
        "interface_declaration" => "interface",
        "enum_declaration" => "enum",
        "record_declaration" => "record",
        "annotation_type_declaration" => "annotation",
        "method_declaration" => "method",
        "constructor_declaration" => "constructor",
        "field_declaration" => "field",
        _ => "declaration",
    }
}
