//! The Java pack.
//!
//! Doc comments are marker text on an ordinary `block_comment`, because the grammar exposes no
//! field and no distinct type for one. `@SuppressWarnings` and friends are **annotations, not
//! comments** — they never reach a rule and need no carve-out.

use crate::common::{
    Container, Excluded, count_members, declarations, declared_name, has_modifier_keyword,
    is_marker_doc, preceding_comment, strip_c_markers,
};
use laconic_engine::domain::{CommentKind, DeclaredSymbol, Visibility};
use laconic_engine::pack::{BlankLinePolicy, DocComment, Pack};
use laconic_grammars::Grammar;
use tree_sitter::Node;

const EXTENSIONS: &[(&str, Grammar)] = &[("java", Grammar::Java)];
pub(crate) const COMMENT_KINDS: &[&str] = &["line_comment", "block_comment"];

/// Concern 3. Bodies arrive with the marker already stripped.
///
/// No `$NON-NLS-` entry. Eclipse emits that marker only as a trailing comment, and no rule reaches a
/// trailing comment since `banner` stopped treating one as a label — so the carve-out protected
/// nothing, and a carve-out that protects nothing makes AC3's third guarantee report work it is not
/// doing. The fixture keeps the marker in its real position as the record of that.
const MACHINE_DIRECTIVES: &[&str] = &[
    "CHECKSTYLE:",
    "SUPPRESS CHECKSTYLE",
    "NOPMD",
    "NOSONAR",
    "@formatter:",
    "spotless:",
];

const GENERATED_MARKERS: &[&str] = &["@generated", "Generated by ", "DO NOT EDIT"];

const TYPES: &[&str] = &[
    "class_declaration",
    "interface_declaration",
    "enum_declaration",
    "record_declaration",
    "annotation_type_declaration",
];

const MEMBERS: &[&str] = &[
    "class_declaration",
    "interface_declaration",
    "enum_declaration",
    "record_declaration",
    "annotation_type_declaration",
    "method_declaration",
    "constructor_declaration",
    "compact_constructor_declaration",
    "field_declaration",
];

const STATEMENTS: Excluded = Excluded {
    reason: "a statement: code that runs, not a name anything can document",
    kinds: &[
        "assert_statement",
        "break_statement",
        "continue_statement",
        "do_statement",
        "enhanced_for_statement",
        "expression_statement",
        "for_statement",
        "if_statement",
        "labeled_statement",
        "return_statement",
        "switch_expression",
        "synchronized_statement",
        "throw_statement",
        "try_statement",
        "try_with_resources_statement",
        "while_statement",
        "yield_statement",
    ],
};

const LOCALS: Excluded = Excluded {
    reason: "a local variable, visible to nothing outside its block",
    kinds: &["local_variable_declaration"],
};

const IMPORTS: Excluded = Excluded {
    reason: "names what the file uses rather than anything it declares",
    kinds: &["import_declaration"],
};

/// The grammar shares one statement rule between the file root and a block; javac accepts these
/// only at the root.
const HEADERS_IN_A_BLOCK: Excluded = Excluded {
    reason: "a file header the grammar tolerates in a block and javac rejects there",
    kinds: &[
        "import_declaration",
        "module_declaration",
        "package_declaration",
    ],
};

const INITIALIZERS: Excluded = Excluded {
    reason: "an initializer runs once and declares nothing a caller can name",
    kinds: &["static_initializer"],
};

/// A method's block is a container because a local class is documented like any other. One in a
/// `switch` group or a brace-less loop body is not reached; javadoc renders no local type, so that
/// loses nothing published.
pub(crate) const CONTAINERS: &[Container] = &[
    Container {
        kind: "program",
        // A `package` or `module` declaration's javadoc is the package or module page itself.
        declarations: &[
            "class_declaration",
            "interface_declaration",
            "enum_declaration",
            "record_declaration",
            "annotation_type_declaration",
            "method_declaration",
            "package_declaration",
            "module_declaration",
        ],
        wrappers: &["block"],
        excluded: &[STATEMENTS, LOCALS, IMPORTS],
    },
    Container {
        kind: "class_body",
        declarations: MEMBERS,
        wrappers: &["block"],
        excluded: &[INITIALIZERS],
    },
    Container {
        kind: "enum_body_declarations",
        declarations: MEMBERS,
        wrappers: &["block"],
        excluded: &[INITIALIZERS],
    },
    Container {
        kind: "enum_body",
        declarations: &["enum_constant"],
        wrappers: &["enum_body_declarations"],
        excluded: &[],
    },
    Container {
        kind: "interface_body",
        declarations: &[
            "class_declaration",
            "interface_declaration",
            "enum_declaration",
            "record_declaration",
            "annotation_type_declaration",
            "method_declaration",
            "constant_declaration",
        ],
        wrappers: &[],
        excluded: &[],
    },
    Container {
        kind: "annotation_type_body",
        declarations: &[
            "class_declaration",
            "interface_declaration",
            "enum_declaration",
            "annotation_type_declaration",
            "annotation_type_element_declaration",
            "constant_declaration",
        ],
        wrappers: &[],
        excluded: &[],
    },
    Container {
        kind: "block",
        declarations: TYPES,
        wrappers: &["block"],
        excluded: &[STATEMENTS, LOCALS, HEADERS_IN_A_BLOCK],
    },
    Container {
        kind: "constructor_body",
        declarations: TYPES,
        wrappers: &["block"],
        excluded: &[
            STATEMENTS,
            LOCALS,
            HEADERS_IN_A_BLOCK,
            Excluded {
                reason: "a `this(…)` or `super(…)` call, which is code",
                kinds: &["explicit_constructor_invocation"],
            },
        ],
    },
];

pub struct JavaPack;

impl Pack for JavaPack {
    fn name(&self) -> &'static str {
        "java"
    }

    fn extensions(&self) -> &[(&'static str, Grammar)] {
        EXTENSIONS
    }

    fn comment_node_kinds(&self, _grammar: Grammar) -> &[&'static str] {
        COMMENT_KINDS
    }

    fn machine_directive_prefixes(&self) -> &[&'static str] {
        MACHINE_DIRECTIVES
    }

    fn generated_file_markers(&self) -> &[&'static str] {
        GENERATED_MARKERS
    }

    fn comment_kind(&self, node: Node, _src: &str) -> CommentKind {
        if node.kind() == "block_comment" {
            CommentKind::Block
        } else {
            CommentKind::Line
        }
    }

    /// Concern 6 — a `/**`-opened block comment directly above a declaration. The marker test is
    /// stricter than `starts_with("/**")`, so `/**/` and `/****/` stay ordinary block comments.
    fn doc_comments<'t>(&self, root: Node<'t>, src: &str) -> Vec<DocComment<'t>> {
        declarations(CONTAINERS, root)
            .into_iter()
            .filter_map(|decl| {
                let comment = preceding_comment(decl, src, COMMENT_KINDS, MACHINE_DIRECTIVES)?;
                (comment.kind() == "block_comment" && is_marker_doc(&src[comment.byte_range()]))
                    .then_some(DocComment {
                        node: comment,
                        subject: decl,
                    })
            })
            .collect()
    }

    fn subject_nodes<'t>(&self, root: Node<'t>) -> Vec<Node<'t>> {
        declarations(CONTAINERS, root)
    }

    fn comment_body(&self, node: Node, src: &str) -> String {
        strip_c_markers(&src[node.byte_range()])
    }

    /// Concern 8 — a keyword child of `modifiers`. No modifier means package-private, which is
    /// reachable from other files in the package and so `Restricted`, not `Private`.
    ///
    /// An enum constant takes its enum's visibility, and an unmarked interface or annotation member
    /// is implicitly public, so it is as visible as the type declaring it. A package or module
    /// declaration is the published page itself.
    fn visibility(&self, subject: Node, _src: &str) -> Visibility {
        java_visibility(subject)
    }

    /// Concern 9. A method's `block` holds statements and a `class_body`, `interface_body` or
    /// `enum_body` holds members; both are the `body` field's named children. A
    /// `field_declaration` names no body and declares none.
    fn member_count(&self, subject: Node, _src: &str) -> usize {
        match subject.child_by_field_name("body") {
            Some(body) => count_members(body, &[]),
            None => 0,
        }
    }

    /// Concern 12 — every Java statement lives in a method inside a class, so a fragment needs both.
    fn statement_scaffold(&self) -> Option<(&'static str, &'static str)> {
        Some(("class Scaffold { void m() {\n", "\n} }\n"))
    }

    fn blank_line_policy(&self) -> BlankLinePolicy {
        BlankLinePolicy::CollapseRun
    }

    fn declared_symbols(&self, root: Node, src: &str) -> Vec<DeclaredSymbol> {
        declarations(CONTAINERS, root)
            .into_iter()
            .filter_map(|decl| {
                // A field declaration names itself through a `variable_declarator`, not a `name`
                // field, so the ordinary path misses every field in the file.
                let name = declared_name(decl, src).or_else(|| field_name(decl, src))?;
                Some(DeclaredSymbol {
                    name: name.to_string(),
                    form: form_of(decl.kind()),
                    visibility: self.visibility(decl, src),
                })
            })
            .collect()
    }
}

fn java_visibility(subject: Node) -> Visibility {
    if matches!(subject.kind(), "package_declaration" | "module_declaration") {
        return Visibility::Exported;
    }
    if subject.kind() == "enum_constant" {
        return enclosing_type(subject).map_or(
            Visibility::Restricted("package".to_string()),
            java_visibility,
        );
    }
    if !has_modifier_keyword(subject, "private")
        && subject
            .parent()
            .is_some_and(|p| matches!(p.kind(), "interface_body" | "annotation_type_body"))
        && let Some(owner) = enclosing_type(subject)
    {
        return java_visibility(owner);
    }
    for (keyword, visibility) in [
        ("public", Visibility::Exported),
        ("private", Visibility::Private),
    ] {
        if has_modifier_keyword(subject, keyword) {
            return visibility;
        }
    }
    if has_modifier_keyword(subject, "protected") {
        return Visibility::Restricted("protected".to_string());
    }
    Visibility::Restricted("package".to_string())
}

fn enclosing_type(member: Node) -> Option<Node> {
    member.parent()?.parent()
}

fn field_name<'a>(decl: Node, src: &'a str) -> Option<&'a str> {
    if !matches!(decl.kind(), "field_declaration" | "constant_declaration") {
        return None;
    }
    let mut cursor = decl.walk();
    let declarator = decl
        .named_children(&mut cursor)
        .find(|n| n.kind() == "variable_declarator")?;
    declared_name(declarator, src)
}

fn form_of(kind: &str) -> &'static str {
    match kind {
        "class_declaration" => "class",
        "interface_declaration" => "interface",
        "enum_declaration" => "enum",
        "record_declaration" => "record",
        "annotation_type_declaration" => "annotation",
        "method_declaration" => "method",
        "constructor_declaration" | "compact_constructor_declaration" => "constructor",
        "field_declaration" | "constant_declaration" => "field",
        "enum_constant" => "constant",
        "annotation_type_element_declaration" => "element",
        _ => "declaration",
    }
}
