//! The Python pack.
//!
//! The awkward one, and every awkwardness is real:
//!
//! - Its doc comment is **not a comment node**. A docstring is a `string`, so concern 2 never finds
//!   one and concern 6 has to enumerate them.
//! - Its doc comment documents the scope that **contains** it, where every other language documents
//!   what follows.
//! - Its docstring therefore sits **inside** the statement container, so it counts as a statement
//!   unless concern 9 discounts it.
//! - It has no visibility construct at all. The leading underscore is a convention a file can
//!   ignore without becoming invalid, which is why this is the one pack answering concern 11 with a
//!   heuristic — and the reversal condition on decision 23 turns on it being the only one.

use crate::common::{count_statements, descendants_of_kind, rows_of};
use laconic_engine::domain::{CommentKind, DeclaredSymbol, Visibility};
use laconic_engine::pack::{BlankLinePolicy, DocComment, Pack};
use laconic_grammars::Grammar;
use tree_sitter::Node;

const EXTENSIONS: &[(&str, Grammar)] = &[("py", Grammar::Python), ("pyi", Grammar::Python)];
const COMMENT_KINDS: &[&str] = &["comment"];

/// Concern 3. Bodies arrive with `#` already stripped, so these match the text that follows it.
///
/// `!` is the shebang: its stripped body is `!/usr/bin/env python3`.
const MACHINE_DIRECTIVES: &[&str] = &[
    "!", "type:", "noqa", "pragma:", "-*-", "coding:", "fmt:", "isort:", "mypy:", "ruff:",
    "flake8:", "pylint:", "nosec",
];

const GENERATED_MARKERS: &[&str] = &["@generated", "Code generated by ", "DO NOT EDIT"];

/// Scopes that can carry a docstring. The module root is the fourth and has no node kind, so it is
/// handled separately.
const SCOPES: &[&str] = &["function_definition", "class_definition"];

pub struct PythonPack;

impl Pack for PythonPack {
    fn name(&self) -> &'static str {
        "python"
    }

    fn extensions(&self) -> &[(&'static str, Grammar)] {
        EXTENSIONS
    }

    fn comment_node_kinds(&self, _grammar: Grammar) -> &[&'static str] {
        COMMENT_KINDS
    }

    fn machine_directive_prefixes(&self) -> &[&'static str] {
        MACHINE_DIRECTIVES
    }

    fn generated_file_markers(&self) -> &[&'static str] {
        GENERATED_MARKERS
    }

    /// Python has no block comment form. Every `comment` node is a Line comment.
    fn comment_kind(&self, _node: Node, _src: &str) -> CommentKind {
        CommentKind::Line
    }

    /// Concern 6 — position, and the subject is the **enclosing** scope.
    ///
    /// A docstring is `(expression_statement (string))` as the first non-comment statement of a
    /// module, class or function body. A string anywhere else is a string, which is why this cannot
    /// be lexical.
    fn doc_comments<'t>(&self, root: Node<'t>, _src: &str) -> Vec<DocComment<'t>> {
        let mut out = Vec::new();
        if let Some(node) = docstring_of(root) {
            out.push(DocComment {
                node,
                subject: root,
            });
        }
        for scope in descendants_of_kind(root, SCOPES) {
            if let Some(body) = scope.child_by_field_name("body")
                && let Some(node) = docstring_of(body)
            {
                out.push(DocComment {
                    node,
                    subject: scope,
                });
            }
        }
        out.sort_by_key(|d| d.node.start_byte());
        out
    }

    fn subject_nodes<'t>(&self, root: Node<'t>) -> Vec<Node<'t>> {
        let mut out = vec![root];
        out.extend(descendants_of_kind(root, SCOPES));
        out
    }

    fn comment_body(&self, node: Node, src: &str) -> String {
        let raw = &src[node.byte_range()];
        raw.strip_prefix('#').unwrap_or(raw).trim_end().to_string()
    }

    /// Concern 8. No visibility construct exists in the grammar, so this is the leading-underscore
    /// convention — reachable by any importer, and `Restricted` rather than `Private` says so.
    fn visibility(&self, subject: Node, src: &str) -> Visibility {
        match subject.child_by_field_name("name") {
            Some(name) if !src[name.byte_range()].starts_with('_') => Visibility::Exported,
            Some(_) => Visibility::Restricted("module".to_string()),
            // The module itself is the file's public surface.
            None => Visibility::Exported,
        }
    }

    /// Concern 9, with the correction the probe found: a docstring is an `expression_statement`
    /// rather than an `extra`, so filtering comments does not remove it here as it does everywhere
    /// else. Left in, the same function shape counts one higher in Python than in any other
    /// language and `density` is systematically harder to trip.
    fn statement_count(&self, subject: Node, _src: &str) -> usize {
        let body = match subject.child_by_field_name("body") {
            Some(body) => body,
            // The module root is its own body.
            None => subject,
        };
        let total = count_statements(body, &[]);
        if docstring_of(body).is_some() {
            total.saturating_sub(1)
        } else {
            total
        }
    }

    /// The module root is its own body for counting statements and is **not** one here: a module
    /// docstring measured against the whole file is a ratio of the file to itself.
    fn body_rows(&self, subject: Node, _src: &str) -> Option<usize> {
        Some(rows_of(subject.child_by_field_name("body")?))
    }

    /// Indentation carries meaning here, so nothing is collapsed: removing a block leaves the
    /// surrounding blank lines exactly as they were.
    fn blank_line_policy(&self) -> BlankLinePolicy {
        BlankLinePolicy::LeaveSurrounding
    }

    fn declared_symbols(&self, root: Node, src: &str) -> Vec<DeclaredSymbol> {
        let mut out = Vec::new();
        let mut cursor = root.walk();
        for decl in root.named_children(&mut cursor) {
            match decl.kind() {
                "function_definition" => push_named(&mut out, decl, "def", src),
                "class_definition" => push_named(&mut out, decl, "class", src),
                // A module-level binding is a declaration too: `_DEFAULT = 3` is exactly the
                // private name a public docstring leaks.
                "expression_statement" => {
                    if let Some(assign) = decl.named_child(0).filter(|n| n.kind() == "assignment")
                        && let Some(left) = assign.child_by_field_name("left")
                    {
                        push_symbol(&mut out, &src[left.byte_range()], "binding");
                    }
                }
                _ => {}
            }
        }
        // Methods are declarations a docstring can name, and they live inside a class body.
        for scope in descendants_of_kind(root, &["class_definition"]) {
            if let Some(body) = scope.child_by_field_name("body") {
                let mut c = body.walk();
                for member in body.named_children(&mut c) {
                    if member.kind() == "function_definition" {
                        push_named(&mut out, member, "def", src);
                    }
                }
            }
        }
        out
    }
}

/// `(expression_statement (string))` as the first non-comment child of a scope.
///
/// First **non-extra**: a shebang or a leading `#` comment sits before a module docstring without
/// displacing it.
fn docstring_of(scope: Node<'_>) -> Option<Node<'_>> {
    let mut cursor = scope.walk();
    let first = scope.named_children(&mut cursor).find(|n| !n.is_extra())?;
    if first.kind() != "expression_statement" {
        return None;
    }
    first.named_child(0).filter(|n| n.kind() == "string")
}

fn push_named(out: &mut Vec<DeclaredSymbol>, node: Node, form: &'static str, src: &str) {
    if let Some(name) = node.child_by_field_name("name") {
        push_symbol(out, &src[name.byte_range()], form);
    }
}

fn push_symbol(out: &mut Vec<DeclaredSymbol>, name: &str, form: &'static str) {
    out.push(DeclaredSymbol {
        visibility: if name.starts_with('_') {
            Visibility::Restricted("module".to_string())
        } else {
            Visibility::Exported
        },
        name: name.to_string(),
        form,
    });
}
