//! The Rust pack.
//!
//! The only language whose doc comment is a **grammar field**. `line_comment` and `block_comment`
//! each carry an optional `doc` child plus `outer`/`inner` marker fields, so `///`, `//!` and `/**`
//! are all answered structurally and this pack never reads a marker.
//!
//! That is not a nicety. A pack reading `///` lexically classifies `////////` as Doc kind, which
//! costs `banner` its gate tier and its Delete fix on exactly the input the rule exists to catch.
//! The grammar declines `////////`, `/**/` and `/*******/` on its own.

use crate::common::{
    Container, Excluded, count_members, declarations, declared_name, descendants_of_kind,
    strip_c_markers,
};
use laconic_engine::domain::{CommentKind, DeclaredSymbol, Visibility};
use laconic_engine::pack::{BlankLinePolicy, DocComment, Pack};
use laconic_grammars::Grammar;
use tree_sitter::Node;

const EXTENSIONS: &[(&str, Grammar)] = &[("rs", Grammar::Rust)];
pub(crate) const COMMENT_KINDS: &[&str] = &["line_comment", "block_comment"];

/// Concern 3.
///
/// Rust's carve-outs are **comment-borne conventions, not tool directives**. rustfmt and clippy are
/// driven by `#[…]` attributes, which are not comments and never reach a rule — `// rustfmt::skip`
/// does not exist and must not be added here.
///
/// `SAFETY:` is required by clippy's `undocumented_unsafe_blocks`, so deleting one breaks a lint.
/// Stripping it as a directive is what makes it unreachable to every rule at once.
const MACHINE_DIRECTIVES: &[&str] = &["SAFETY:", "cbindgen:", "grcov-excl", "coverage:"];

const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "Code generated by ",
    "DO NOT EDIT",
    "Generated by ",
];

/// Items that can carry a doc comment wherever an item can appear. `function_signature_item` is a
/// trait method without a body, or a function in an `extern` block.
const ITEMS: &[&str] = &[
    "function_item",
    "function_signature_item",
    "struct_item",
    "enum_item",
    "union_item",
    "trait_item",
    "impl_item",
    "mod_item",
    "type_item",
    "const_item",
    "static_item",
    "macro_definition",
];

const TRAIT_OR_IMPL_ITEMS: &[&str] = &[
    "function_item",
    "function_signature_item",
    "struct_item",
    "enum_item",
    "union_item",
    "trait_item",
    "impl_item",
    "mod_item",
    "type_item",
    "const_item",
    "static_item",
    "macro_definition",
    "associated_type",
];

const ATTRIBUTES: Excluded = Excluded {
    reason: "an attribute annotates the item after it or the module around it",
    kinds: NON_STATEMENTS,
};

const OUTER_ATTRIBUTES: Excluded = Excluded {
    reason: "an attribute annotates the field or variant after it",
    kinds: &["attribute_item"],
};

const IMPORTS: Excluded = Excluded {
    reason: "names what the module uses rather than anything it declares",
    kinds: &["use_declaration", "extern_crate_declaration"],
};

const EXTERN_BLOCKS: Excluded = Excluded {
    reason: "an `extern` block, whose functions are the declarations",
    kinds: &["foreign_mod_item"],
};

const MACRO_CALLS: Excluded = Excluded {
    reason: "a macro call, whose expansion the grammar cannot see",
    kinds: &["macro_invocation"],
};

pub(crate) const CONTAINERS: &[Container] = &[
    Container {
        kind: "source_file",
        declarations: ITEMS,
        wrappers: &[],
        excluded: &[
            ATTRIBUTES,
            IMPORTS,
            EXTERN_BLOCKS,
            MACRO_CALLS,
            Excluded {
                reason: "a statement or trait member the grammar accepts at file scope and rustc \
                         rejects",
                kinds: &[
                    "associated_type",
                    "empty_statement",
                    "expression_statement",
                    "let_declaration",
                ],
            },
            Excluded {
                reason: "the interpreter line, read by the shell",
                kinds: &["shebang"],
            },
        ],
    },
    // The body of a `mod`, an `impl`, a `trait` and an `extern` block alike.
    Container {
        kind: "declaration_list",
        declarations: TRAIT_OR_IMPL_ITEMS,
        wrappers: &[],
        excluded: &[
            ATTRIBUTES,
            IMPORTS,
            EXTERN_BLOCKS,
            MACRO_CALLS,
            Excluded {
                reason: "a statement the grammar accepts in an item list and rustc rejects",
                kinds: &["empty_statement", "let_declaration"],
            },
        ],
    },
    // An item nested in a function body is documented like any other.
    Container {
        kind: "block",
        declarations: ITEMS,
        wrappers: &[],
        excluded: &[
            ATTRIBUTES,
            IMPORTS,
            EXTERN_BLOCKS,
            MACRO_CALLS,
            Excluded {
                reason: "a trait member the grammar accepts in a block and rustc rejects",
                kinds: &["associated_type"],
            },
            Excluded {
                reason: "a statement or expression: code that runs, not a name anything can document",
                kinds: &[
                    "array_expression",
                    "assignment_expression",
                    "async_block",
                    "await_expression",
                    "binary_expression",
                    "block",
                    "boolean_literal",
                    "break_expression",
                    "call_expression",
                    "char_literal",
                    "closure_expression",
                    "compound_assignment_expr",
                    "const_block",
                    "continue_expression",
                    "empty_statement",
                    "expression_statement",
                    "field_expression",
                    "float_literal",
                    "for_expression",
                    "gen_block",
                    "generic_function",
                    "identifier",
                    "if_expression",
                    "index_expression",
                    "integer_literal",
                    "label",
                    "let_declaration",
                    "loop_expression",
                    "match_expression",
                    "metavariable",
                    "parenthesized_expression",
                    "range_expression",
                    "raw_string_literal",
                    "reference_expression",
                    "return_expression",
                    "scoped_identifier",
                    "self",
                    "string_literal",
                    "struct_expression",
                    "try_block",
                    "try_expression",
                    "tuple_expression",
                    "type_cast_expression",
                    "unary_expression",
                    "unit_expression",
                    "unsafe_block",
                    "while_expression",
                    "yield_expression",
                ],
            },
        ],
    },
    Container {
        kind: "field_declaration_list",
        declarations: &["field_declaration"],
        wrappers: &[],
        excluded: &[OUTER_ATTRIBUTES],
    },
    Container {
        kind: "enum_variant_list",
        declarations: &["enum_variant"],
        wrappers: &[],
        excluded: &[OUTER_ATTRIBUTES],
    },
];

/// Named children of a block that are not statements. A statement-level attribute inflates
/// `member_count` by one per attribute, which is `docbloat`'s denominator.
pub(crate) const NON_STATEMENTS: &[&str] = &["attribute_item", "inner_attribute_item"];

pub struct RustPack;

impl Pack for RustPack {
    fn name(&self) -> &'static str {
        "rust"
    }

    fn extensions(&self) -> &[(&'static str, Grammar)] {
        EXTENSIONS
    }

    fn comment_node_kinds(&self, _grammar: Grammar) -> &[&'static str] {
        COMMENT_KINDS
    }

    fn machine_directive_prefixes(&self) -> &[&'static str] {
        MACHINE_DIRECTIVES
    }

    fn generated_file_markers(&self) -> &[&'static str] {
        GENERATED_MARKERS
    }

    fn comment_kind(&self, node: Node, _src: &str) -> CommentKind {
        if node.kind() == "block_comment" {
            CommentKind::Block
        } else {
            CommentKind::Line
        }
    }

    /// Concern 6 — the `doc` field, never the marker.
    ///
    /// `outer` (`///`, `/**`) documents the item that follows. `inner` (`//!`) documents the module
    /// that contains it, which is the same inversion Python has and for a different reason.
    fn doc_comments<'t>(&self, root: Node<'t>, _src: &str) -> Vec<DocComment<'t>> {
        let mut out = Vec::new();
        for comment in descendants_of_kind(root, COMMENT_KINDS) {
            if comment.child_by_field_name("doc").is_none() {
                continue;
            }
            let subject = if comment.child_by_field_name("inner").is_some() {
                enclosing_module(comment, root)
            } else {
                following_item(comment)
            };
            if let Some(subject) = subject {
                out.push(DocComment {
                    node: comment,
                    subject,
                });
            }
        }
        out
    }

    fn subject_nodes<'t>(&self, root: Node<'t>) -> Vec<Node<'t>> {
        let mut out = vec![root];
        out.extend(declarations(CONTAINERS, root));
        out
    }

    /// Concern 7, and Rust answers half of it from the grammar: the `doc` child is the body with
    /// its markers already removed.
    fn comment_body(&self, node: Node, src: &str) -> String {
        match node.child_by_field_name("doc") {
            Some(doc) => src[doc.byte_range()].trim_end().to_string(),
            None => strip_c_markers(&src[node.byte_range()]),
        }
    }

    /// Concern 8. `visibility_modifier` read as **text**, not as presence: `pub`, `pub(crate)` and
    /// `pub(self)` are one node kind and three different answers, and `pub(self)` is private.
    /// An `enum_variant` has no visibility of its own: Rust forbids `pub` on a variant because a
    /// variant inherits its enum's. Reading the absent modifier as `Private` made every variant of
    /// every public enum a private symbol, so `implInInterface` fired on the words a doc comment
    /// uses to name them — `Line`, `Block`, `Doc`.
    fn visibility(&self, subject: Node, src: &str) -> Visibility {
        // A trait's members carry no `pub` either, and are as reachable as the trait.
        if let Some(trait_item) = subject
            .parent()
            .and_then(|list| list.parent())
            .filter(|owner| owner.kind() == "trait_item")
        {
            return self.visibility(trait_item, src);
        }
        if subject.kind() == "enum_variant" {
            let mut ancestor = subject.parent();
            while let Some(node) = ancestor {
                if node.kind() == "enum_item" {
                    return self.visibility(node, src);
                }
                ancestor = node.parent();
            }
            return Visibility::Private;
        }
        let mut cursor = subject.walk();
        let modifier = subject
            .named_children(&mut cursor)
            .find(|n| n.kind() == "visibility_modifier")
            .map(|n| &src[n.byte_range()]);
        match modifier {
            Some("pub") => Visibility::Exported,
            Some("pub(self)") => Visibility::Private,
            Some(other) => Visibility::Restricted(other.to_string()),
            // A file is usually a module, so an item with no modifier is not reachable from
            // outside it.
            None => Visibility::Private,
        }
    }

    /// Concern 9. Every Rust container names its members through a `body` field — a function's
    /// `block`, a struct's field list, an enum's variant list, a trait's declaration list — so one
    /// walk answers all of them. A `const_item`, a `type_item` and the file root name none.
    fn member_count(&self, subject: Node, _src: &str) -> usize {
        match subject.child_by_field_name("body") {
            Some(body) => count_members(body, NON_STATEMENTS),
            None => 0,
        }
    }

    /// Concern 12 — statements are not items, so a fragment parses only inside a function.
    fn statement_scaffold(&self) -> Option<(&'static str, &'static str)> {
        Some(("fn scaffold() {\n", "\n}\n"))
    }

    fn blank_line_policy(&self) -> BlankLinePolicy {
        BlankLinePolicy::CollapseRun
    }

    fn declared_symbols(&self, root: Node, src: &str) -> Vec<DeclaredSymbol> {
        declarations(CONTAINERS, root)
            .into_iter()
            .filter_map(|item| {
                let name = declared_name(item, src)?;
                Some(DeclaredSymbol {
                    name: name.to_string(),
                    form: form_of(item.kind()),
                    visibility: if in_trait_impl(item) {
                        Visibility::Exported
                    } else {
                        self.visibility(item, src)
                    },
                })
            })
            .collect()
    }
}

/// Whether an item is a member of a **trait** impl — `impl Display for Foo`, not `impl Foo`.
///
/// Such a member carries no `pub` and is reachable by anyone with the trait in scope, so reporting
/// it as unexported is a category error rather than a strict reading. `impl Default for Thresholds`
/// declares `default` and `impl From<A> for B` declares `from`, which made those two words
/// unusable in every doc comment in the file — including sentences where the word is plain English.
///
/// The `trait` field is what separates the two impl forms; an inherent `impl Foo { fn helper() }`
/// has none, and its private methods really are private.
fn in_trait_impl(item: Node) -> bool {
    let mut node = item.parent();
    while let Some(current) = node {
        if current.kind() == "impl_item" {
            return current.child_by_field_name("trait").is_some();
        }
        node = current.parent();
    }
    false
}

fn form_of(kind: &str) -> &'static str {
    match kind {
        "function_item" | "function_signature_item" => "fn",
        "struct_item" => "struct",
        "enum_item" => "enum",
        "union_item" => "union",
        "trait_item" => "trait",
        "impl_item" => "impl",
        "mod_item" => "mod",
        "type_item" | "associated_type" => "type",
        "const_item" => "const",
        "static_item" => "static",
        "macro_definition" => "macro",
        "field_declaration" => "field",
        "enum_variant" => "variant",
        _ => "item",
    }
}

/// The item a `///` or `/**` comment documents: the next sibling that is not itself a comment or an
/// attribute, since attributes sit between a doc comment and its item.
fn following_item(comment: Node<'_>) -> Option<Node<'_>> {
    let mut next = comment.next_named_sibling();
    while let Some(node) = next {
        if !node.is_extra() && !NON_STATEMENTS.contains(&node.kind()) {
            return Some(node);
        }
        next = node.next_named_sibling();
    }
    None
}

/// The module a `//!` comment documents — the nearest `mod_item` above it, or the file.
fn enclosing_module<'t>(comment: Node<'t>, root: Node<'t>) -> Option<Node<'t>> {
    let mut parent = comment.parent();
    while let Some(node) = parent {
        if node.kind() == "mod_item" {
            return Some(node);
        }
        parent = node.parent();
    }
    Some(root)
}
