//! The Rust pack.
//!
//! The only language whose doc comment is a **grammar field**. `line_comment` and `block_comment`
//! each carry an optional `doc` child plus `outer`/`inner` marker fields, so `///`, `//!` and `/**`
//! are all answered structurally and this pack never reads a marker.
//!
//! That is not a nicety. A pack reading `///` lexically classifies `////////` as Doc kind, which
//! costs `banner` its gate tier and its Delete fix on exactly the input the rule exists to catch.
//! The grammar declines `////////`, `/**/` and `/*******/` on its own.

use crate::common::{count_members, declared_name, descendants_of_kind, strip_c_markers};
use laconic_engine::domain::{CommentKind, DeclaredSymbol, Visibility};
use laconic_engine::pack::{BlankLinePolicy, DocComment, Pack};
use laconic_grammars::Grammar;
use tree_sitter::Node;

const EXTENSIONS: &[(&str, Grammar)] = &[("rs", Grammar::Rust)];
pub(crate) const COMMENT_KINDS: &[&str] = &["line_comment", "block_comment"];

/// Concern 3.
///
/// Rust's carve-outs are **comment-borne conventions, not tool directives**. rustfmt and clippy are
/// driven by `#[…]` attributes, which are not comments and never reach a rule — `// rustfmt::skip`
/// does not exist and must not be added here.
///
/// `SAFETY:` is required by clippy's `undocumented_unsafe_blocks`, so deleting one breaks a lint.
/// Stripping it as a directive is what makes it unreachable to every rule at once.
const MACHINE_DIRECTIVES: &[&str] = &["SAFETY:", "cbindgen:", "grcov-excl", "coverage:"];

const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "Code generated by ",
    "DO NOT EDIT",
    "Generated by ",
];

/// Items that can carry a doc comment.
pub(crate) const ITEMS: &[&str] = &[
    "function_item",
    "struct_item",
    "enum_item",
    "union_item",
    "trait_item",
    "impl_item",
    "mod_item",
    "type_item",
    "const_item",
    "static_item",
    "macro_definition",
    "field_declaration",
    "enum_variant",
];

/// Named children of a block that are not statements. A statement-level attribute inflates
/// `density`'s denominator by one per attribute.
pub(crate) const NON_STATEMENTS: &[&str] = &["attribute_item", "inner_attribute_item"];

pub struct RustPack;

impl Pack for RustPack {
    fn name(&self) -> &'static str {
        "rust"
    }

    fn extensions(&self) -> &[(&'static str, Grammar)] {
        EXTENSIONS
    }

    fn comment_node_kinds(&self, _grammar: Grammar) -> &[&'static str] {
        COMMENT_KINDS
    }

    fn machine_directive_prefixes(&self) -> &[&'static str] {
        MACHINE_DIRECTIVES
    }

    fn generated_file_markers(&self) -> &[&'static str] {
        GENERATED_MARKERS
    }

    fn comment_kind(&self, node: Node, _src: &str) -> CommentKind {
        if node.kind() == "block_comment" {
            CommentKind::Block
        } else {
            CommentKind::Line
        }
    }

    /// Concern 6 — the `doc` field, never the marker.
    ///
    /// `outer` (`///`, `/**`) documents the item that follows. `inner` (`//!`) documents the module
    /// that contains it, which is the same inversion Python has and for a different reason.
    fn doc_comments<'t>(&self, root: Node<'t>, _src: &str) -> Vec<DocComment<'t>> {
        let mut out = Vec::new();
        for comment in descendants_of_kind(root, COMMENT_KINDS) {
            if comment.child_by_field_name("doc").is_none() {
                continue;
            }
            let subject = if comment.child_by_field_name("inner").is_some() {
                enclosing_module(comment, root)
            } else {
                following_item(comment)
            };
            if let Some(subject) = subject {
                out.push(DocComment {
                    node: comment,
                    subject,
                });
            }
        }
        out
    }

    fn subject_nodes<'t>(&self, root: Node<'t>) -> Vec<Node<'t>> {
        let mut out = vec![root];
        out.extend(descendants_of_kind(root, ITEMS));
        out
    }

    /// Concern 7, and Rust answers half of it from the grammar: the `doc` child is the body with
    /// its markers already removed.
    fn comment_body(&self, node: Node, src: &str) -> String {
        match node.child_by_field_name("doc") {
            Some(doc) => src[doc.byte_range()].trim_end().to_string(),
            None => strip_c_markers(&src[node.byte_range()]),
        }
    }

    /// Concern 8. `visibility_modifier` read as **text**, not as presence: `pub`, `pub(crate)` and
    /// `pub(self)` are one node kind and three different answers, and `pub(self)` is private.
    /// An `enum_variant` has no visibility of its own: Rust forbids `pub` on a variant because a
    /// variant inherits its enum's. Reading the absent modifier as `Private` made every variant of
    /// every public enum a private symbol, so `implInInterface` fired on the words a doc comment
    /// uses to name them — `Line`, `Block`, `Doc`.
    fn visibility(&self, subject: Node, src: &str) -> Visibility {
        if subject.kind() == "enum_variant" {
            let mut ancestor = subject.parent();
            while let Some(node) = ancestor {
                if node.kind() == "enum_item" {
                    return self.visibility(node, src);
                }
                ancestor = node.parent();
            }
            return Visibility::Private;
        }
        let mut cursor = subject.walk();
        let modifier = subject
            .named_children(&mut cursor)
            .find(|n| n.kind() == "visibility_modifier")
            .map(|n| &src[n.byte_range()]);
        match modifier {
            Some("pub") => Visibility::Exported,
            Some("pub(self)") => Visibility::Private,
            Some(other) => Visibility::Restricted(other.to_string()),
            // A file is usually a module, so an item with no modifier is not reachable from
            // outside it.
            None => Visibility::Private,
        }
    }

    /// Concern 9. Every Rust container names its members through a `body` field — a function's
    /// `block`, a struct's field list, an enum's variant list, a trait's declaration list — so one
    /// walk answers all of them. A `const_item`, a `type_item` and the file root name none.
    fn member_count(&self, subject: Node, _src: &str) -> usize {
        match subject.child_by_field_name("body") {
            Some(body) => count_members(body, NON_STATEMENTS),
            None => 0,
        }
    }

    fn blank_line_policy(&self) -> BlankLinePolicy {
        BlankLinePolicy::CollapseRun
    }

    fn declared_symbols(&self, root: Node, src: &str) -> Vec<DeclaredSymbol> {
        descendants_of_kind(root, ITEMS)
            .into_iter()
            .filter_map(|item| {
                let name = declared_name(item, src)?;
                Some(DeclaredSymbol {
                    name: name.to_string(),
                    form: form_of(item.kind()),
                    visibility: self.visibility(item, src),
                })
            })
            .collect()
    }
}

fn form_of(kind: &str) -> &'static str {
    match kind {
        "function_item" => "fn",
        "struct_item" => "struct",
        "enum_item" => "enum",
        "union_item" => "union",
        "trait_item" => "trait",
        "impl_item" => "impl",
        "mod_item" => "mod",
        "type_item" => "type",
        "const_item" => "const",
        "static_item" => "static",
        "macro_definition" => "macro",
        "field_declaration" => "field",
        "enum_variant" => "variant",
        _ => "item",
    }
}

/// The item a `///` or `/**` comment documents: the next sibling that is not itself a comment or an
/// attribute, since attributes sit between a doc comment and its item.
fn following_item(comment: Node<'_>) -> Option<Node<'_>> {
    let mut next = comment.next_named_sibling();
    while let Some(node) = next {
        if !node.is_extra() && !NON_STATEMENTS.contains(&node.kind()) {
            return Some(node);
        }
        next = node.next_named_sibling();
    }
    None
}

/// The module a `//!` comment documents — the nearest `mod_item` above it, or the file.
fn enclosing_module<'t>(comment: Node<'t>, root: Node<'t>) -> Option<Node<'t>> {
    let mut parent = comment.parent();
    while let Some(node) = parent {
        if node.kind() == "mod_item" {
            return Some(node);
        }
        parent = node.parent();
    }
    Some(root)
}
