//! The Swift pack.
//!
//! Doc comments are marker text, as in Java: the grammar gives `///`, `// MARK:` and `//` one node
//! kind and `/** */` the same kind as `/* */`. Class, struct, enum, actor and extension are one
//! `class_declaration`, told apart by its `declaration_kind` field.

use crate::common::{
    Container, Excluded, count_members, declarations, is_marker_doc, preceding_comment,
    strip_c_markers,
};
use laconic_engine::domain::{CommentKind, DeclaredSymbol, Visibility};
use laconic_engine::pack::{BlankLinePolicy, DocComment, Pack};
use laconic_grammars::Grammar;
use tree_sitter::Node;

const EXTENSIONS: &[(&str, Grammar)] = &[("swift", Grammar::Swift)];
pub(crate) const COMMENT_KINDS: &[&str] = &["comment", "multiline_comment"];

/// Concern 3. Bodies arrive with the marker stripped.
///
/// `MARK:` builds Xcode's jump bar and SwiftLint checks its format, and it is exactly the shape
/// `banner` deletes. `sourcery:inline` and `sourcery:end` bracket generated code, so removing one
/// corrupts the next regeneration. `TODO:` and `FIXME:` are read by SwiftLint only to warn about
/// them, and stay subject to the rules as in every other pack.
const MACHINE_DIRECTIVES: &[&str] = &[
    "MARK:",
    "swiftlint:",
    "swift-format-ignore",
    "swiftformat:",
    "sourcery:",
    "periphery:ignore",
];

const GENERATED_MARKERS: &[&str] = &[
    "Generated using Sourcery",
    "Generated using SwiftGen",
    "@generated",
    "Code generated by ",
    "DO NOT EDIT",
];

const MEMBERS: &[&str] = &[
    "class_declaration",
    "protocol_declaration",
    "function_declaration",
    "init_declaration",
    "deinit_declaration",
    "subscript_declaration",
    "property_declaration",
    "typealias_declaration",
];

const CODE: &[&str] = &[
    "additive_expression",
    "array_literal",
    "as_expression",
    "assignment",
    "await_expression",
    "bang",
    "bin_literal",
    "bitwise_operation",
    "boolean_literal",
    "call_expression",
    "check_expression",
    "comparison_expression",
    "conjunction_expression",
    "constructor_expression",
    "consume_expression",
    "custom_operator",
    "dictionary_literal",
    "discard_statement",
    "disjunction_expression",
    "do_statement",
    "equality_expression",
    "for_statement",
    "fully_open_range",
    "guard_statement",
    "hex_literal",
    "if_statement",
    "infix_expression",
    "integer_literal",
    "key_path_expression",
    "key_path_string_expression",
    "lambda_literal",
    "line_string_literal",
    "multi_line_string_literal",
    "multiplicative_expression",
    "navigation_expression",
    "nil_coalescing_expression",
    "oct_literal",
    "open_end_range_expression",
    "open_start_range_expression",
    "playground_literal",
    "postfix_expression",
    "prefix_expression",
    "range_expression",
    "raw_string_literal",
    "real_literal",
    "regex_literal",
    "repeat_while_statement",
    "selector_expression",
    "self_expression",
    "simple_identifier",
    "special_literal",
    "statement_label",
    "super_expression",
    "switch_statement",
    "ternary_expression",
    "try_expression",
    "tuple_expression",
    "value_pack_expansion",
    "value_parameter_pack",
    "while_statement",
];

const COMPILER_DIRECTIVES: Excluded = Excluded {
    reason: "a compiler directive — `#if`, `#warning` — which declares nothing",
    kinds: &["directive", "diagnostic"],
};

const CONDITIONAL_COMPILATION: Excluded = Excluded {
    reason: "an `#if` directive, which declares nothing",
    kinds: &["directive"],
};

const MACRO_CALLS: Excluded = Excluded {
    reason: "a freestanding macro call such as `#Preview`, whose expansion the grammar cannot see",
    kinds: &["macro_invocation"],
};

/// The grammar accepts these in a type body; swiftc accepts them only at file scope or in a
/// protocol.
const MISPLACED_IN_A_TYPE: Excluded = Excluded {
    reason: "a declaration the grammar tolerates in a type body and swiftc rejects there",
    kinds: &[
        "associatedtype_declaration",
        "import_declaration",
        "operator_declaration",
        "precedence_group_declaration",
    ],
};

pub(crate) const CONTAINERS: &[Container] = &[
    Container {
        kind: "source_file",
        declarations: &[
            "class_declaration",
            "protocol_declaration",
            "function_declaration",
            "property_declaration",
            "typealias_declaration",
            "macro_declaration",
            "operator_declaration",
            "precedence_group_declaration",
        ],
        wrappers: &[],
        excluded: &[
            COMPILER_DIRECTIVES,
            MACRO_CALLS,
            Excluded {
                reason: "names what the file uses rather than anything it declares",
                kinds: &["import_declaration"],
            },
            Excluded {
                reason: "a member the grammar tolerates at file scope and swiftc rejects there",
                kinds: &["associatedtype_declaration", "init_declaration"],
            },
            Excluded {
                reason: "top-level code in `main.swift` or a script: it runs, and names nothing",
                kinds: CODE,
            },
            Excluded {
                reason: "top-level code in `main.swift` or a script: it runs, and names nothing",
                kinds: &["throw_keyword"],
            },
            Excluded {
                reason: "the interpreter line, read by the shell",
                kinds: &["shebang_line"],
            },
        ],
    },
    Container {
        kind: "class_body",
        declarations: MEMBERS,
        wrappers: &[],
        excluded: &[
            CONDITIONAL_COMPILATION,
            MISPLACED_IN_A_TYPE,
            Excluded {
                reason: "a comment, which the grammar lists here as well as everywhere else",
                kinds: &["multiline_comment"],
            },
        ],
    },
    Container {
        kind: "enum_class_body",
        declarations: &[
            "enum_entry",
            "class_declaration",
            "protocol_declaration",
            "function_declaration",
            "init_declaration",
            "deinit_declaration",
            "subscript_declaration",
            "property_declaration",
            "typealias_declaration",
        ],
        wrappers: &[],
        excluded: &[CONDITIONAL_COMPILATION, MISPLACED_IN_A_TYPE],
    },
    Container {
        kind: "protocol_body",
        declarations: &[
            "protocol_function_declaration",
            "protocol_property_declaration",
            "init_declaration",
            "subscript_declaration",
            "associatedtype_declaration",
            "typealias_declaration",
        ],
        wrappers: &[],
        excluded: &[
            CONDITIONAL_COMPILATION,
            Excluded {
                reason: "a `deinit` the grammar tolerates in a protocol and swiftc rejects",
                kinds: &["deinit_declaration"],
            },
        ],
    },
    // A function, closure or accessor body. A nested function or type is documented like any
    // other; a `let` or `var` here is a local.
    Container {
        kind: "statements",
        declarations: &[
            "class_declaration",
            "function_declaration",
            "typealias_declaration",
        ],
        wrappers: &[],
        excluded: &[
            COMPILER_DIRECTIVES,
            MACRO_CALLS,
            Excluded {
                reason: "a local binding, visible to nothing outside its body",
                kinds: &["property_declaration"],
            },
            Excluded {
                reason: "a statement or expression: code that runs, not a name anything can document",
                kinds: CODE,
            },
            Excluded {
                reason: "a statement or expression: code that runs, not a name anything can document",
                kinds: &["control_transfer_statement"],
            },
        ],
    },
];

pub struct SwiftPack;

impl Pack for SwiftPack {
    fn name(&self) -> &'static str {
        "swift"
    }

    fn extensions(&self) -> &[(&'static str, Grammar)] {
        EXTENSIONS
    }

    fn comment_node_kinds(&self, _grammar: Grammar) -> &[&'static str] {
        COMMENT_KINDS
    }

    fn machine_directive_prefixes(&self) -> &[&'static str] {
        MACHINE_DIRECTIVES
    }

    fn generated_file_markers(&self) -> &[&'static str] {
        GENERATED_MARKERS
    }

    fn comment_kind(&self, node: Node, _src: &str) -> CommentKind {
        if node.kind() == "multiline_comment" {
            CommentKind::Block
        } else {
            CommentKind::Line
        }
    }

    /// Concern 6 — a `///` or `/**` comment directly above a declaration. `////` and `/**/` open
    /// with the same characters and are banners, not documentation.
    fn doc_comments<'t>(&self, root: Node<'t>, src: &str) -> Vec<DocComment<'t>> {
        declarations(CONTAINERS, root)
            .into_iter()
            .filter_map(|decl| {
                let comment = preceding_comment(decl, src, COMMENT_KINDS, MACHINE_DIRECTIVES)?;
                is_doc(&src[comment.byte_range()]).then_some(DocComment {
                    node: comment,
                    subject: decl,
                })
            })
            .collect()
    }

    fn subject_nodes<'t>(&self, root: Node<'t>) -> Vec<Node<'t>> {
        declarations(CONTAINERS, root)
    }

    /// `///` loses all three slashes. `strip_c_markers` removes two, and a doc body that opens with
    /// `/` reads as punctuation to `banner`.
    fn comment_body(&self, node: Node, src: &str) -> String {
        let raw = &src[node.byte_range()];
        match raw.strip_prefix("///") {
            Some(rest) => rest.trim_end().to_string(),
            None => strip_c_markers(raw),
        }
    }

    /// Concern 8. A member with no modifier of its own is as visible as Swift makes it: a protocol
    /// requirement and an enum case take their owner's visibility, a member of a `public
    /// extension` is public, and anything else is internal — never more visible than a private
    /// owner.
    fn visibility(&self, subject: Node, src: &str) -> Visibility {
        if let Some(own) = own_visibility(subject, src) {
            return own;
        }
        let Some(owner) = subject.parent().and_then(|body| body.parent()) else {
            return internal();
        };
        let owner_visibility = || self.visibility(owner, src);
        match owner.kind() {
            "protocol_declaration" => owner_visibility(),
            "class_declaration" if subject.kind() == "enum_entry" => owner_visibility(),
            "class_declaration" if declaration_kind(owner, src) == Some("extension") => {
                own_visibility(owner, src).unwrap_or_else(internal)
            }
            "class_declaration" => match owner_visibility() {
                Visibility::Private => Visibility::Private,
                _ => internal(),
            },
            _ => internal(),
        }
    }

    /// Concern 9. A body's members are its statements when it has a `statements` child — a
    /// function, an initializer, a computed property — and its declarations otherwise.
    fn member_count(&self, subject: Node, _src: &str) -> usize {
        let mut cursor = subject.walk();
        let body = subject.child_by_field_name("body").or_else(|| {
            subject
                .named_children(&mut cursor)
                .find(|n| n.kind() == "computed_property")
        });
        let Some(body) = body else {
            return 0;
        };
        let mut cursor = body.walk();
        let statements = body
            .named_children(&mut cursor)
            .find(|n| n.kind() == "statements");
        count_members(statements.unwrap_or(body), &[])
    }

    fn statement_scaffold(&self) -> Option<(&'static str, &'static str)> {
        Some(("func scaffold() {\n", "\n}\n"))
    }

    fn blank_line_policy(&self) -> BlankLinePolicy {
        BlankLinePolicy::CollapseRun
    }

    /// Concern 11. An extension declares no name of its own, and an initializer, deinitializer or
    /// subscript is not a name a comment can mention.
    fn declared_symbols(&self, root: Node, src: &str) -> Vec<DeclaredSymbol> {
        let mut out = Vec::new();
        for decl in declarations(CONTAINERS, root) {
            let form = match decl.kind() {
                "class_declaration" => match declaration_kind(decl, src) {
                    Some("class") => "class",
                    Some("struct") => "struct",
                    Some("enum") => "enum",
                    Some("actor") => "actor",
                    _ => continue,
                },
                "protocol_declaration" => "protocol",
                "function_declaration" | "protocol_function_declaration" => "func",
                "property_declaration" | "protocol_property_declaration" => "var",
                "enum_entry" => "case",
                "typealias_declaration" | "associatedtype_declaration" => "type",
                "macro_declaration" => "macro",
                _ => continue,
            };
            let visibility = self.visibility(decl, src);
            let mut cursor = decl.walk();
            for name in decl.children_by_field_name("name", &mut cursor) {
                // A property's name is a pattern; the identifier it binds is inside.
                let name = name.child_by_field_name("bound_identifier").unwrap_or(name);
                out.push(DeclaredSymbol {
                    name: src[name.byte_range()].to_string(),
                    form,
                    visibility: visibility.clone(),
                });
                // A typealias names its alias first and the aliased type second.
                if form == "type" {
                    break;
                }
            }
        }
        out
    }
}

fn is_doc(raw: &str) -> bool {
    match raw.strip_prefix("///") {
        Some(rest) => !rest.starts_with('/'),
        None => is_marker_doc(raw),
    }
}

/// The member's own modifier. `private(set)` restricts the setter, not the declaration.
fn own_visibility(node: Node, src: &str) -> Option<Visibility> {
    let mut cursor = node.walk();
    let modifiers = node
        .named_children(&mut cursor)
        .find(|n| n.kind() == "modifiers")?;
    let mut cursor = modifiers.walk();
    let text = modifiers
        .named_children(&mut cursor)
        .filter(|n| n.kind() == "visibility_modifier")
        .map(|n| &src[n.byte_range()])
        .find(|t| !t.ends_with("(set)"))?;
    Some(match text {
        "public" | "open" => Visibility::Exported,
        "private" | "fileprivate" => Visibility::Private,
        "package" => Visibility::Restricted("package".to_string()),
        _ => internal(),
    })
}

fn internal() -> Visibility {
    Visibility::Restricted("module".to_string())
}

/// `class`, `struct`, `enum`, `actor` or `extension`: the keyword the grammar records as a field.
fn declaration_kind<'a>(decl: Node, src: &'a str) -> Option<&'a str> {
    decl.child_by_field_name("declaration_kind")
        .map(|n| &src[n.byte_range()])
}
