//! The TypeScript / JavaScript pack — **one pack over three grammars**.
//!
//! `tree-sitter-typescript` exports two language functions and JavaScript is a separate crate, so
//! the grammar is selected per extension rather than per pack. All three answer concerns 6 and 8
//! identically, which is what makes one pack over three grammars viable rather than a compromise.
//!
//! All three also emit `html_comment` — the legacy `<!--` form — alongside `comment`. It is in
//! scope: it is a comment, it can carry narration, and leaving it out would make `<!-- changed to
//! use a map -->` invisible to every rule.

use crate::common::{
    Container, Excluded, count_members, declarations, declared_name, descendants_of_kind,
    is_declaration, is_exported_declaration, is_marker_doc, outermost_wrapper, preceding_comment,
    strip_c_markers, visibility_from_export,
};
use laconic_engine::domain::{CommentKind, DeclaredSymbol, Visibility};
use laconic_engine::pack::{BlankLinePolicy, DocComment, Pack};
use laconic_grammars::Grammar;
use tree_sitter::Node;

const EXTENSIONS: &[(&str, Grammar)] = &[
    ("ts", Grammar::TypeScript),
    ("mts", Grammar::TypeScript),
    ("cts", Grammar::TypeScript),
    ("tsx", Grammar::Tsx),
    ("js", Grammar::JavaScript),
    ("mjs", Grammar::JavaScript),
    ("cjs", Grammar::JavaScript),
    ("jsx", Grammar::JavaScript),
];

pub(crate) const COMMENT_KINDS: &[&str] = &["comment", "html_comment"];

/// Concern 3. Bodies arrive with `//` or `/* */` already stripped, so `/// <reference …>` becomes
/// `/ <reference …>` and `//# sourceMappingURL=` becomes `# sourceMappingURL=`.
const MACHINE_DIRECTIVES: &[&str] = &[
    "@ts-",
    "eslint",
    "prettier-ignore",
    "istanbul ignore",
    "c8 ignore",
    "v8 ignore",
    "biome-ignore",
    "@formatter:",
    "/ <reference",
    "# sourceMappingURL",
    "webpackChunkName",
    "@jsx",
    "@license",
    "@preserve",
];

const GENERATED_MARKERS: &[&str] = &["@generated", "Code generated by ", "DO NOT EDIT"];

const MODULE_MEMBERS: &[&str] = &[
    "function_declaration",
    "generator_function_declaration",
    "function_signature",
    "class_declaration",
    "abstract_class_declaration",
    "interface_declaration",
    "enum_declaration",
    "type_alias_declaration",
    "internal_module",
    "module",
    "lexical_declaration",
    "variable_declaration",
];

/// A function body can declare a nested function or type, and nothing it binds is visible outside.
const LOCAL_DECLARATIONS: &[&str] = &[
    "function_declaration",
    "generator_function_declaration",
    "function_signature",
    "class_declaration",
    "abstract_class_declaration",
    "interface_declaration",
    "enum_declaration",
    "type_alias_declaration",
    "internal_module",
    "module",
];

const STATEMENTS: Excluded = Excluded {
    reason: "a statement: code that runs, not a name anything can document",
    kinds: &[
        "break_statement",
        "continue_statement",
        "debugger_statement",
        "do_statement",
        "empty_statement",
        "for_in_statement",
        "for_statement",
        "if_statement",
        "labeled_statement",
        "return_statement",
        "switch_statement",
        "throw_statement",
        "try_statement",
        "while_statement",
        "with_statement",
    ],
};

/// The grammar parses a top-level `namespace N {}` as an expression statement around the namespace.
const STATEMENT_WRAPPERS: &[&str] = &[
    "export_statement",
    "ambient_declaration",
    "statement_block",
    "expression_statement",
];

const IMPORTS: Excluded = Excluded {
    reason: "names what the file uses rather than anything it declares",
    kinds: &["import_statement", "import_alias"],
};

const LOCALS: Excluded = Excluded {
    reason: "a local binding, visible to nothing outside its block",
    kinds: &[
        "lexical_declaration",
        "variable_declaration",
        "using_declaration",
    ],
};

const SIGNATURES: &[&str] = &[
    "method_signature",
    "property_signature",
    "index_signature",
    "call_signature",
    "construct_signature",
];

/// The grammar allows `export` inside an interface or a type literal; tsc does not.
const EXPORT_IN_A_TYPE: Excluded = Excluded {
    reason: "an `export` the grammar tolerates in a type body and tsc rejects",
    kinds: &["export_statement"],
};

pub(crate) const CONTAINERS: &[Container] = &[
    Container {
        kind: "program",
        within: &[],
        declarations: MODULE_MEMBERS,
        wrappers: STATEMENT_WRAPPERS,
        excluded: &[
            STATEMENTS,
            IMPORTS,
            Excluded {
                reason: "disposed at the end of its scope, so never part of a module's surface",
                kinds: &["using_declaration"],
            },
            Excluded {
                reason: "the interpreter line, read by the shell",
                kinds: &["hash_bang_line"],
            },
        ],
    },
    // A namespace, `declare module` or `declare global` body: a `const` there is a module member.
    Container {
        kind: "statement_block",
        within: &["internal_module", "module", "ambient_declaration"],
        declarations: MODULE_MEMBERS,
        wrappers: STATEMENT_WRAPPERS,
        excluded: &[
            STATEMENTS,
            IMPORTS,
            Excluded {
                reason: "disposed at the end of its scope, so never part of a module's surface",
                kinds: &["using_declaration"],
            },
        ],
    },
    Container {
        kind: "statement_block",
        within: &[],
        declarations: LOCAL_DECLARATIONS,
        wrappers: STATEMENT_WRAPPERS,
        excluded: &[STATEMENTS, IMPORTS, LOCALS],
    },
    Container {
        kind: "export_statement",
        within: &[],
        declarations: &[
            "function_declaration",
            "generator_function_declaration",
            "function_signature",
            "class_declaration",
            "abstract_class_declaration",
            "interface_declaration",
            "enum_declaration",
            "type_alias_declaration",
            "internal_module",
            "module",
            "lexical_declaration",
            "variable_declaration",
            // `export default` of an anonymous class or function, documented like a named one.
            "class",
            "function_expression",
            "generator_function",
            "arrow_function",
        ],
        // An exported object's methods are documented like any other.
        wrappers: &["ambient_declaration", "object"],
        excluded: &[
            Excluded {
                reason: "`export default` of a plain value, which names nothing a reader looks up",
                kinds: &[
                    "array",
                    "as_expression",
                    "assignment_expression",
                    "augmented_assignment_expression",
                    "await_expression",
                    "binary_expression",
                    "call_expression",
                    "false",
                    "identifier",
                    "instantiation_expression",
                    "jsx_element",
                    "jsx_self_closing_element",
                    "member_expression",
                    "meta_property",
                    "new_expression",
                    "non_null_expression",
                    "null",
                    "number",
                    "parenthesized_expression",
                    "regex",
                    "satisfies_expression",
                    "string",
                    "subscript_expression",
                    "super",
                    "template_string",
                    "ternary_expression",
                    "this",
                    "true",
                    "type_assertion",
                    "unary_expression",
                    "undefined",
                    "update_expression",
                    "yield_expression",
                ],
            },
            Excluded {
                reason: "re-exports a name declared elsewhere",
                kinds: &["export_clause", "namespace_export", "import_alias"],
            },
            Excluded {
                reason: "annotates the class after it",
                kinds: &["decorator"],
            },
            Excluded {
                reason: "disposed at the end of its scope, so never part of a module's surface",
                kinds: &["using_declaration"],
            },
        ],
    },
    Container {
        kind: "ambient_declaration",
        within: &[],
        declarations: &[
            "function_declaration",
            "generator_function_declaration",
            "function_signature",
            "class_declaration",
            "abstract_class_declaration",
            "interface_declaration",
            "enum_declaration",
            "type_alias_declaration",
            "internal_module",
            "module",
            "lexical_declaration",
            "variable_declaration",
        ],
        wrappers: &["ambient_declaration", "statement_block"],
        excluded: &[
            Excluded {
                reason: "names what the file uses rather than anything it declares",
                kinds: &["import_alias"],
            },
            Excluded {
                reason: "part of a `declare module.name: type` header rather than a declaration",
                kinds: &[
                    "array_type",
                    "call_expression",
                    "conditional_type",
                    "constructor_type",
                    "existential_type",
                    "flow_maybe_type",
                    "function_type",
                    "generic_type",
                    "index_type_query",
                    "infer_type",
                    "intersection_type",
                    "literal_type",
                    "lookup_type",
                    "member_expression",
                    "nested_type_identifier",
                    "object_type",
                    "parenthesized_type",
                    "predefined_type",
                    "property_identifier",
                    "readonly_type",
                    "template_literal_type",
                    "this_type",
                    "tuple_type",
                    "type_identifier",
                    "type_query",
                    "union_type",
                ],
            },
        ],
    },
    Container {
        kind: "class_body",
        within: &[],
        declarations: &[
            "method_definition",
            "method_signature",
            "abstract_method_signature",
            "public_field_definition",
            "field_definition",
            "index_signature",
        ],
        wrappers: &[],
        excluded: &[
            Excluded {
                reason: "annotates the member after it",
                kinds: &["decorator"],
            },
            Excluded {
                reason: "a static block runs once and declares nothing a caller can name",
                kinds: &["class_static_block"],
            },
        ],
    },
    Container {
        kind: "interface_body",
        within: &[],
        declarations: SIGNATURES,
        wrappers: &[],
        excluded: &[EXPORT_IN_A_TYPE],
    },
    Container {
        kind: "object_type",
        within: &[],
        declarations: SIGNATURES,
        wrappers: &[],
        excluded: &[EXPORT_IN_A_TYPE],
    },
    // Every form an enum member's name can take.
    Container {
        kind: "enum_body",
        within: &[],
        declarations: &[
            "property_identifier",
            "enum_assignment",
            "string",
            "number",
            "computed_property_name",
            "private_property_identifier",
        ],
        wrappers: &[],
        excluded: &[],
    },
    Container {
        kind: "object",
        within: &[],
        declarations: &["method_definition"],
        wrappers: &[],
        excluded: &[Excluded {
            reason: "a property value, which declares nothing apart from the object",
            kinds: &["pair", "shorthand_property_identifier", "spread_element"],
        }],
    },
];

/// Body kinds whose named children are the subject's members — pack concern 9.
///
/// Every entry is reachable as some node's `body` field in a grammar this pack claims, which
/// `grammar_conformance` is what checks. `object_type` was here and is not: no node in either the
/// TypeScript or the TSX grammar names one as `body`, so the filter never had it to exclude.
pub(crate) const MEMBER_CONTAINERS: &[&str] = &[
    "statement_block",
    "class_body",
    "interface_body",
    "enum_body",
];

pub struct TypeScriptPack;

impl Pack for TypeScriptPack {
    fn name(&self) -> &'static str {
        "typescript"
    }

    fn extensions(&self) -> &[(&'static str, Grammar)] {
        EXTENSIONS
    }

    fn comment_node_kinds(&self, _grammar: Grammar) -> &[&'static str] {
        COMMENT_KINDS
    }

    fn machine_directive_prefixes(&self) -> &[&'static str] {
        MACHINE_DIRECTIVES
    }

    fn generated_file_markers(&self) -> &[&'static str] {
        GENERATED_MARKERS
    }

    /// An `html_comment` runs to end of line, which makes it Line whatever it contains.
    fn comment_kind(&self, node: Node, src: &str) -> CommentKind {
        if node.kind() == "html_comment" {
            return CommentKind::Line;
        }
        if src[node.byte_range()].starts_with("/*") {
            CommentKind::Block
        } else {
            CommentKind::Line
        }
    }

    /// Concern 6 — marker text above the declaration, or above the `export` or `declare` wrapping
    /// it: in `export declare function f` the comment's sibling is the `export_statement`.
    fn doc_comments<'t>(&self, root: Node<'t>, src: &str) -> Vec<DocComment<'t>> {
        declarations(CONTAINERS, root)
            .into_iter()
            .filter_map(|decl| {
                let anchor = outermost_wrapper(decl);
                let comment = preceding_comment(anchor, src, COMMENT_KINDS, MACHINE_DIRECTIVES)?;
                is_marker_doc(&src[comment.byte_range()]).then_some(DocComment {
                    node: comment,
                    subject: decl,
                })
            })
            .collect()
    }

    fn subject_nodes<'t>(&self, root: Node<'t>) -> Vec<Node<'t>> {
        declarations(CONTAINERS, root)
    }

    fn comment_body(&self, node: Node, src: &str) -> String {
        let raw = &src[node.byte_range()];
        match raw.strip_prefix("<!--").and_then(|r| r.strip_suffix("-->")) {
            Some(inner) => inner.trim_end().to_string(),
            None => strip_c_markers(raw),
        }
    }

    /// Concern 8 — two unrelated questions in one language. At file scope it is the
    /// `export_statement` wrapper; on a class member it is an `accessibility_modifier`. An enum
    /// member or a signature in an interface or type literal has no visibility of its own and takes
    /// that of the nearest declaration around it.
    fn visibility(&self, subject: Node, src: &str) -> Visibility {
        if subject.parent().is_some_and(|body| {
            matches!(body.kind(), "enum_body" | "interface_body" | "object_type")
        }) {
            let mut owner = subject.parent();
            while let Some(node) = owner {
                if is_declaration(CONTAINERS, node) {
                    return self.visibility(node, src);
                }
                owner = node.parent();
            }
            return Visibility::Restricted("module".to_string());
        }
        let mut cursor = subject.walk();
        let accessibility = subject
            .children(&mut cursor)
            .find(|n| n.kind() == "accessibility_modifier")
            .map(|n| &src[n.byte_range()]);
        match accessibility {
            Some("private") => return Visibility::Private,
            Some("protected") => return Visibility::Restricted("protected".to_string()),
            // A member marked `public` is public only if its class is reachable, but the class is
            // the subject that answers that; here the member's own answer is what is asked for.
            Some(_) => return Visibility::Exported,
            None => {}
        }
        visibility_from_export(subject)
    }

    /// Concern 9. A declaration added to [`CONTAINERS`] whose body holds something other than
    /// members or statements counts nothing instead of counting rows.
    fn member_count(&self, subject: Node, _src: &str) -> usize {
        match subject.child_by_field_name("body") {
            Some(body) if MEMBER_CONTAINERS.contains(&body.kind()) => count_members(body, &[]),
            _ => 0,
        }
    }

    fn blank_line_policy(&self) -> BlankLinePolicy {
        BlankLinePolicy::CollapseRun
    }

    fn declared_symbols(&self, root: Node, src: &str) -> Vec<DeclaredSymbol> {
        let mut out: Vec<DeclaredSymbol> = declarations(CONTAINERS, root)
            .into_iter()
            .filter_map(|decl| {
                // These name a key parameter or nothing, never a member.
                if matches!(
                    decl.kind(),
                    "index_signature" | "call_signature" | "construct_signature"
                ) {
                    return None;
                }
                let name = declared_name(decl, src)?;
                Some(DeclaredSymbol {
                    name: name.to_string(),
                    form: form_of(decl.kind()),
                    visibility: self.visibility(decl, src),
                })
            })
            .collect();

        // `const` and `let` name themselves through a `variable_declarator`, not a `name` field —
        // and a module-private const is exactly the name a public JSDoc leaks.
        for decl in descendants_of_kind(root, &["lexical_declaration", "variable_declaration"]) {
            let exported = is_exported_declaration(decl);
            let mut cursor = decl.walk();
            for declarator in decl.named_children(&mut cursor) {
                if declarator.kind() != "variable_declarator" {
                    continue;
                }
                if let Some(name) = declared_name(declarator, src) {
                    out.push(DeclaredSymbol {
                        name: name.to_string(),
                        form: "binding",
                        visibility: if exported {
                            Visibility::Exported
                        } else {
                            Visibility::Restricted("module".to_string())
                        },
                    });
                }
            }
        }
        out.sort_by(|a, b| a.name.cmp(&b.name));
        out
    }
}

fn form_of(kind: &str) -> &'static str {
    match kind {
        "function_declaration" | "generator_function_declaration" => "function",
        "class_declaration" | "abstract_class_declaration" => "class",
        "interface_declaration" => "interface",
        "enum_declaration" => "enum",
        "type_alias_declaration" => "type",
        "method_definition" => "method",
        "public_field_definition" => "field",
        _ => "declaration",
    }
}
