//! The TypeScript / JavaScript pack — **one pack over three grammars**.
//!
//! `tree-sitter-typescript` exports two language functions and JavaScript is a separate crate, so
//! the grammar is selected per extension rather than per pack. All three answer concerns 6 and 8
//! identically, which is what makes one pack over three grammars viable rather than a compromise.
//!
//! All three also emit `html_comment` — the legacy `<!--` form — alongside `comment`. It is in
//! scope: it is a comment, it can carry narration, and leaving it out would make `<!-- changed to
//! use a map -->` invisible to every rule.

use crate::common::{
    count_members, declared_name, descendants_of_kind, is_exported_declaration, is_marker_doc,
    preceding_comment, strip_c_markers, visibility_from_export,
};
use laconic_engine::domain::{CommentKind, DeclaredSymbol, Visibility};
use laconic_engine::pack::{BlankLinePolicy, DocComment, Pack};
use laconic_grammars::Grammar;
use tree_sitter::Node;

const EXTENSIONS: &[(&str, Grammar)] = &[
    ("ts", Grammar::TypeScript),
    ("mts", Grammar::TypeScript),
    ("cts", Grammar::TypeScript),
    ("tsx", Grammar::Tsx),
    ("js", Grammar::JavaScript),
    ("mjs", Grammar::JavaScript),
    ("cjs", Grammar::JavaScript),
    ("jsx", Grammar::JavaScript),
];

pub(crate) const COMMENT_KINDS: &[&str] = &["comment", "html_comment"];

/// Concern 3. Bodies arrive with `//` or `/* */` already stripped, so `/// <reference …>` becomes
/// `/ <reference …>` and `//# sourceMappingURL=` becomes `# sourceMappingURL=`.
const MACHINE_DIRECTIVES: &[&str] = &[
    "@ts-",
    "eslint",
    "prettier-ignore",
    "istanbul ignore",
    "c8 ignore",
    "v8 ignore",
    "biome-ignore",
    "@formatter:",
    "/ <reference",
    "# sourceMappingURL",
    "webpackChunkName",
    "@jsx",
    "@license",
    "@preserve",
];

const GENERATED_MARKERS: &[&str] = &["@generated", "Code generated by ", "DO NOT EDIT"];

pub(crate) const DECLARATIONS: &[&str] = &[
    "function_declaration",
    "generator_function_declaration",
    "class_declaration",
    "interface_declaration",
    "enum_declaration",
    "type_alias_declaration",
    "method_definition",
    "public_field_definition",
    "abstract_class_declaration",
];

/// Body kinds whose named children are the subject's members — pack concern 9.
///
/// Every entry is reachable as some node's `body` field in a grammar this pack claims, which
/// `grammar_conformance` is what checks. `object_type` was here and is not: no node in either the
/// TypeScript or the TSX grammar names one as `body`, so the filter never had it to exclude.
pub(crate) const MEMBER_CONTAINERS: &[&str] = &[
    "statement_block",
    "class_body",
    "interface_body",
    "enum_body",
];

pub struct TypeScriptPack;

impl Pack for TypeScriptPack {
    fn name(&self) -> &'static str {
        "typescript"
    }

    fn extensions(&self) -> &[(&'static str, Grammar)] {
        EXTENSIONS
    }

    fn comment_node_kinds(&self, _grammar: Grammar) -> &[&'static str] {
        COMMENT_KINDS
    }

    fn machine_directive_prefixes(&self) -> &[&'static str] {
        MACHINE_DIRECTIVES
    }

    fn generated_file_markers(&self) -> &[&'static str] {
        GENERATED_MARKERS
    }

    /// An `html_comment` runs to end of line, which makes it Line whatever it contains.
    fn comment_kind(&self, node: Node, src: &str) -> CommentKind {
        if node.kind() == "html_comment" {
            return CommentKind::Line;
        }
        if src[node.byte_range()].starts_with("/*") {
            CommentKind::Block
        } else {
            CommentKind::Line
        }
    }

    /// Concern 6 — marker text, on the declaration or on the `export` statement wrapping it. A
    /// JSDoc comment sits above `export function f`, so the comment's sibling is the
    /// `export_statement` and not the declaration it documents.
    fn doc_comments<'t>(&self, root: Node<'t>, src: &str) -> Vec<DocComment<'t>> {
        descendants_of_kind(root, DECLARATIONS)
            .into_iter()
            .filter_map(|decl| {
                let anchor = if is_exported_declaration(decl) {
                    decl.parent()?
                } else {
                    decl
                };
                let comment = preceding_comment(anchor, src, COMMENT_KINDS, MACHINE_DIRECTIVES)?;
                is_marker_doc(&src[comment.byte_range()]).then_some(DocComment {
                    node: comment,
                    subject: decl,
                })
            })
            .collect()
    }

    fn subject_nodes<'t>(&self, root: Node<'t>) -> Vec<Node<'t>> {
        descendants_of_kind(root, DECLARATIONS)
    }

    fn comment_body(&self, node: Node, src: &str) -> String {
        let raw = &src[node.byte_range()];
        match raw.strip_prefix("<!--").and_then(|r| r.strip_suffix("-->")) {
            Some(inner) => inner.trim_end().to_string(),
            None => strip_c_markers(raw),
        }
    }

    /// Concern 8 — two unrelated questions in one language. At file scope it is the
    /// `export_statement` wrapper; on a class member it is an `accessibility_modifier`.
    fn visibility(&self, subject: Node, src: &str) -> Visibility {
        let _ = src;
        let mut cursor = subject.walk();
        let accessibility = subject
            .children(&mut cursor)
            .find(|n| n.kind() == "accessibility_modifier")
            .map(|n| &src[n.byte_range()]);
        match accessibility {
            Some("private") => return Visibility::Private,
            Some("protected") => return Visibility::Restricted("protected".to_string()),
            // A member marked `public` is public only if its class is reachable, but the class is
            // the subject that answers that; here the member's own answer is what is asked for.
            Some(_) => return Visibility::Exported,
            None => {}
        }
        visibility_from_export(subject)
    }

    /// Concern 9. The allowlist is what keeps this from counting the named children of a body that
    /// holds no members: a `switch_statement` names a `switch_body`, and the statement forms name a
    /// bare `statement`, neither of which a comment documents. Both reach here, because
    /// `descendants_of_kind` walks the whole tree and a member of [`DECLARATIONS`] can nest inside
    /// either.
    ///
    /// It is not what excludes a type alias or an arrow function, which the previous wording
    /// claimed: `type_alias_declaration` names no `body` field at all — its value is a `value` —
    /// and `arrow_function` is not in [`DECLARATIONS`], so neither ever reaches this match.
    fn member_count(&self, subject: Node, _src: &str) -> usize {
        match subject.child_by_field_name("body") {
            Some(body) if MEMBER_CONTAINERS.contains(&body.kind()) => count_members(body, &[]),
            _ => 0,
        }
    }

    fn blank_line_policy(&self) -> BlankLinePolicy {
        BlankLinePolicy::CollapseRun
    }

    fn declared_symbols(&self, root: Node, src: &str) -> Vec<DeclaredSymbol> {
        let mut out: Vec<DeclaredSymbol> = descendants_of_kind(root, DECLARATIONS)
            .into_iter()
            .filter_map(|decl| {
                let name = declared_name(decl, src)?;
                Some(DeclaredSymbol {
                    name: name.to_string(),
                    form: form_of(decl.kind()),
                    visibility: self.visibility(decl, src),
                })
            })
            .collect();

        // `const` and `let` bind through a `variable_declarator`, so the declaration walk above
        // never sees them — and a module-private const is exactly the name a public JSDoc leaks.
        for decl in descendants_of_kind(root, &["lexical_declaration", "variable_declaration"]) {
            let exported = is_exported_declaration(decl);
            let mut cursor = decl.walk();
            for declarator in decl.named_children(&mut cursor) {
                if declarator.kind() != "variable_declarator" {
                    continue;
                }
                if let Some(name) = declared_name(declarator, src) {
                    out.push(DeclaredSymbol {
                        name: name.to_string(),
                        form: "binding",
                        visibility: if exported {
                            Visibility::Exported
                        } else {
                            Visibility::Restricted("module".to_string())
                        },
                    });
                }
            }
        }
        out.sort_by(|a, b| a.name.cmp(&b.name));
        out
    }
}

fn form_of(kind: &str) -> &'static str {
    match kind {
        "function_declaration" | "generator_function_declaration" => "function",
        "class_declaration" | "abstract_class_declaration" => "class",
        "interface_declaration" => "interface",
        "enum_declaration" => "enum",
        "type_alias_declaration" => "type",
        "method_definition" => "method",
        "public_field_definition" => "field",
        _ => "declaration",
    }
}
